### ISSUE TITLE
aws operator 2.7.2 helm chart namespaced options?

### ISSUE THREAD

**Issue by ifelsefi** [ansible/tower-operator#1627] opened 2023-11-08 19:25 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am trying to deploy namespaced operator via helm chart but it keeps creating clusterroles, clusterrolebindings, etc, which we do not want.  

Per #541 this [should](https://github.com/ansible/awx-operator/pull/541#issuecomment-921445978) be possible:

```
This PR has been updated to move the awx-operator from a cluster-scoped operator to a namespace-scoped operator. At a high level this means only Roles for service accounts, no ClusterRoles, and it also means that operators & AWX deployments will have a 1-to-1 relationship.
```

Yet I cannot figure out the correct `values.yaml`.

### AWX Operator version

2.7.2

### AWX version

latest

### Kubernetes platform

Rancher 2.7

### Kubernetes/Platform version

1.24.10

### Modifications

no

### Steps to reproduce

`wget https://github.com/ansible/awx-operator/releases/download/2.7.2/awx-operator-2.7.2.tgz`

`helm upgrade --install -v8 -n ti-ansible-awx ti-ansible-awx ./awx-operator-2.7.2.tgz -f myvalues.yaml`

```
---
AWX:
  enabled: true
  spec:
    image_version: 2.7.2
```

### Expected results

installs without need for clusterrolebindings

### Actual results

creates clusterroles, clusterrolebinding, and fails:

```
I1108 12:44:03.813284   25185 request.go:1188] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"awxs.awx.ansible.com \"awx\" is forbidden: User \"u-ouq5l5qa3n\" cannot get resource \"awxs\" in API group \"awx.ansible.com\" in the namespace \"ti-ansible-awx\"","reason":"Forbidden","details":{"name":"awx","group":"awx.ansible.com","kind":"awxs"},"code":403}
Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource AWX "awx" in namespace "ti-ansible-awx": awxs.awx.ansible.com "awx" is forbidden: User "u-ouq5l5qa3n" cannot get resource "awxs" in API group "awx.ansible.com" in the namespace "ti-ansible-awx"
```

**Comment by oraNod** [comment] 2024-09-04 18:34
Hi @ifelsefi 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:34 UTC
Labels: needs_triage, community, Helm
