### ISSUE TITLE
Installing awx operator 19.0 Internal Server Error

### ISSUE THREAD

**Issue by Tyler-Ouellette** [ansible/tower-operator#218] opened 2021-04-16 12:17 UTC
ISSUE TYPE
Bug Report
SUMMARY
When installing awx I am getting this error:
```
Failure\\\",\\\"message\\\":\\\"Internal error occurred: failed calling webhook \\\\\\\\\\\"validate.nginx.ingress.kubernetes.io\\\\\\\\\\\": an error on the server (\\\\\\\\\\\"\\\\\\\\\\\") has prevented the request from succeeding\\\",\\\"reason\\\":\\\"InternalError\\\",\\\"details\\\":{\\\"causes\\\":[{\\\"message\\\":\\\"failed calling webhook \\\\\\\\\\\"validate.nginx.ingress.kubernetes.io\\\\\\\\\\\": an error on the server (\\\\\\\\\\\"\\\\\\\\\\\") has prevented the request from succeeding\\\"}]},\\\"code\\\":500}\\\\n'\", \"reason\": \"Internal Server Error\", \"status\": 500}\n\r\n
PLAY RECAP *********************************************************************\r\nlocalhost                  : ok=27   changed=0    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0   \r\n\r\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=27   changed=0    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0   \r\n\n","job":"2740103009342231109","name":"awx","namespace":"default","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:239"}
{"level":"error","ts":1618575259.4156518,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
```

Internal 500 error due to zapper?

ENVIRONMENT
AWX version: 19.0
AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker
Ansible version: ansible 2.9.6
Operating System: Ubuntu 20.04
Web Browser: mozilla

STEPS TO REPRODUCE
From a fresh Ubuntu 20.04 instance with Virtualization enabled.
```
sudo apt-get update
sudo apt upgrade -y
sudo apt install docker.io -y
sudo systemctl enable --now docker

if you need to Disable Docker at startup:
sudo systemctl disable --now docker

User Perms
sudo usermod -aG docker tyler
docker –version

Docker is good. Next install Kubectl
sudo apt-get update
sudo apt-get install apt-transport-https
sudo apt-get upgrade
sudo apt install virtualbox virtualbox-ext-pack

wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube-linux-amd64
sudo mv minikube-linux-amd64 /usr/local/bin/minikube
minikube version

sudo apt install curl
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x ./kubectl

sudo mv ./kubectl /usr/local/bin/kubectl

kubectl version -o json

Good to use minikube

minikube start

Start minikube for AWX
minikube start --cpus=4 --memory=8g --addons=ingress

minikube kubectl -- apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml

Wait until it is ready
Nano install-awx-playbook.yml
---
  apiVersion: awx.ansible.com/v1beta1
  kind: AWX
  metadata:
  name: awx
  spec:
    tower_ingress_type: Ingress

minikube kubectl apply -- -f install-awx-playbook.yml

To see logs of the install run this:
minikube kubectl logs -- -f awx-operator-ID from your pod
minikube kubectl logs -- -f awx-operator-f768499d-zn7zc

After running you should run

minikube kubectl get pods

To Access AWX
minikube service awx-service –url
http://192.168.49.2:31417
Once you go to the IP:Port address you probably see AWX is currently upgrading. Once it does, you will be redirected to a login screen. To get login info run:

minikube kubectl -- get secret awx-admin-password -o jsonpath='{.data.password}' | base64 –decode
```

EXPECTED RESULTS
AWX to work, instead I am stuck on upgrading AWX screen:

ACTUAL RESULTS
Stuck at migrations notran page.
```
minikube kubectl apply -- -f install-awx-playbook.yml
awx.awx.ansible.com/awx unchanged

tyler@tyler-VirtualBox:~$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
awx-b5f6cf4d4-7rfwg           4/4     Running          12                  2d16h
awx-operator-f768499d-zn7zc   1/1     Running   4              2d16h
awx-postgres-0                      1/1     Running   3                     2d16h


minikube kubectl logs -- -f awx-operator-f768499d-zn7zc
```

```
Getting this error in the tailed logs:
435-408a-8a18-a4178a85b5f7\\\"}\": {\".\": {}, \"f:apiVersion\": {}, \"f:kind\": {}, \"f:name\": {}, \"f:uid\": {}}}}, \"f:spec\": {\"f:externalTrafficPolicy\": {}, \"f:ports\": {\".\": {}, \"k:{\\\"port\\\":80,\\\"protocol\\\":\\\"TCP\\\"}\": {\".\": {}, \"f:name\": {}, \"f:port\": {}, \"f:protocol\": {}, \"f:targetPort\": {}}}, \"f:selector\": {\".\": {}, \"f:app.kubernetes.io/component\": {}, \"f:app.kubernetes.io/managed-by\": {}, \"f:app.kubernetes.io/name\": {}}, \"f:sessionAffinity\": {}, \"f:type\": {}}}, \"manager\": \"Swagger-Codegen\", \"operation\": \"Update\", \"time\": \"2021-04-13T19:42:37Z\"}], \"name\": \"awx-service\", \"namespace\": \"default\", \"ownerReferences\": [{\"apiVersion\": \"awx.ansible.com/v1beta1\", \"kind\": \"AWX\", \"name\": \"awx\", \"uid\": \"5271a041-b435-408a-8a18-a4178a85b5f7\"}], \"resourceVersion\": \"973\", \"uid\": \"438cec5c-40c6-4d0f-a415-6e5ad36b5696\"}, \"spec\": {\"clusterIP\": \"10.96.209.235\", \"clusterIPs\": [\"10.96.209.235\"], \"externalTrafficPolicy\": \"Cluster\", \"ports\": [{\"name\": \"http\", \"nodePort\": 31417, \"port\": 80, \"protocol\": \"TCP\", \"targetPort\": 8052}], \"selector\": {\"app.kubernetes.io/component\": \"awx\", \"app.kubernetes.io/managed-by\": \"awx-operator\", \"app.kubernetes.io/name\": \"awx\"}, \"sessionAffinity\": \"None\", \"type\": \"NodePort\"}, \"status\": {\"loadBalancer\": {}}}}\nfailed: [localhost] (item=tower_ingress) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"error\": 500, \"item\": \"tower_ingress\", \"msg\": \"Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\**"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Internal error occurred: failed calling webhook \\\\\\\\\\\"validate.nginx.ingress.kubernetes.io\\\\\\\\\\\": an error on the server (\\\\\\\\\\\"\\\\\\\\\\\") has prevented the request from succeeding\\\",\\\"reason\\\":\\\"InternalError\\\",\\\"details\\\":{\\\"causes\\\":[{\\\"message\\\":\\\"failed calling webhook \\\\\\\\\\\"validate.nginx.ingress.kubernetes.io\\\\\\\\\\\": an error on the server (\\\\\\\\\\\"\\\\\\\\\\\") has prevented the request from succeeding\\\"}]},\\\"code\\\":500}\\\\n'\", \"reason\": \"Internal Server Error\", \"status\": 500}\n\r\nPLAY RECAP** *********************************************************************\r\nlocalhost                  : ok=27   changed=0    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0   \r\n\r\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=27   changed=0    unreachable=0    failed=1    skipped=25   rescued=0    ignored=0   \r\n\n","job":"2740103009342231109","name":"awx","namespace":"default","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:239"}
{"level":"error","ts":1618575259.4156518,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

```

**Comment by bhundven** [comment] 2021-04-16 17:54
Duplicate of #205
I also provide a work-around in that issue.

**Comment by Tyler-Ouellette** [comment] 2021-04-16 18:38
@bhundven I have used the work around, do i have to then revert minikube? I ran the commands to delete:

$ kubectl get validatingwebhookconfigurations
$ kubectl delete -A ValidatingWebhookConfiguration [configuration-name]

mine is the asame as yours: ingress-nginx-admission

so when i run that, and then redeploy the yaml. still does the same thing.

**Comment by Tyler-Ouellette** [comment] 2021-04-16 18:39
```
tyler@tyler-VirtualBox:~$ kubectl get validatingwebhookconfigurations
NAME                      WEBHOOKS   AGE
ingress-nginx-admission   1          2m25s
tyler@tyler-VirtualBox:~$ kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
validatingwebhookconfiguration.admissionregistration.k8s.io "ingress-nginx-admission" deleted
```
still same error :(

**Comment by diegoturcios** [comment] 2021-04-17 01:04
I confirm it works in redhat with this version of minikube: https://storage.googleapis.com/minikube/releases/latest/minikube-1.18.1-0.x86_64.rpm

**Comment by tchellomello** [comment] 2021-04-17 02:23
Closing as duplicate of #205

**Closed as completed by tchellomello** 2021-04-17 02:23 UTC

**Comment by Tyler-Ouellette** [comment] 2021-04-19 15:12
Had to use 1.8 but thank you
