### ISSUE TITLE
New tech preview UI allow user who dont have project create permission to create new project 

### ISSUE THREAD

**Issue by dkoci** [ansible/tower-operator#1594] opened 2023-10-16 11:55 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I create normal user who does not the have permission to create projects, inventories etc. Then I switched to new tech preview UI. After that user get the ability to create projects, inventories etc on main dashboard.
Is there any option to disable the new tech preview option enabling?

"Old" UI:
<img width="1140" alt="image" src="https://github.com/ansible/awx-operator/assets/5565897/d092d332-af44-4cba-a884-05f0ff2b9bf8">

New tech preview UI:
<img width="1038" alt="image" src="https://github.com/ansible/awx-operator/assets/5565897/8d6be57d-eefd-435f-85ab-feb0df4f16c4">

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.13

### Modifications

no

### Steps to reproduce

Create normal user. Switch to new tech preview UI. Normal user can create project on the main dashboard.

### Expected results

Normal user can not create new projects, inventories.

### Actual results

Normal user can create project on the main dashboard eveh he does not have additional permission for project creation.

**Comment by kurokobo** [comment] 2023-10-16 15:28
> Is there any option to disable the new tech preview option enabling?

You can disable New UI by `Settings` > `Miscellaneous System settings` > `Enable Preview of New User Interface`.

> Normal user can create project on the main dashboard eveh he does not have additional permission for project creation.

Quickly tested, I can confirm that normal user can open "Create Project" page from dashboard indeed, but actual request to create project (by click "Create project" button) is rejected by API:

![image](https://github.com/ansible/awx-operator/assets/2920259/aac8ad90-7da6-48e3-ba10-6c6615b2e1ef)

![image](https://github.com/ansible/awx-operator/assets/2920259/3580676c-907a-49f3-9565-7d070205dcb4)

Also "Projects" page is prohibited as expected:

![image](https://github.com/ansible/awx-operator/assets/2920259/e28f1a9a-00ad-4ebe-9a3c-7ea61ac2b0bc)

So this is a dashboard issue, not an API issue.

**Comment by TheRealHaoLiu** [comment] 2023-10-16 20:22
Thanks @kurokobo ❤️

Closing the issue since the user won't actually have ability to create project. 

@dkoci can u submit a issue against ansible-ui

**Closed as not planned** 2023-10-16 20:22 UTC
Labels: needs_triage, community

**Comment by dkoci** [comment] 2023-10-17 08:19
Ofc I will. I didnt even know this is the separate project.
