### ISSUE TITLE
Receptor implementation

### ISSUE THREAD

**Issue by whoamiUNIX** [ansible/tower-operator#790] opened 2022-02-11 15:09 UTC
Is there plan to include https://github.com/ansible/receptor into operator ?

It sounds as perfect feature to have receptor integrated to be able reach isoleted receptor node.

**Comment by rhessing** [comment] 2022-02-11 15:17
They are implementing it at this moment, the last stable version already contains some commands to register a receptor node and a hop node. However, I have not been able to get this to work, even tried to adjust the template files within the operator but no luck.

**Comment by whoamiUNIX** [comment] 2022-02-11 15:39
@rhessing in that case would be nice to have documentation.

**Comment by rebeccahhh** [comment] 2022-02-11 18:20
hey there, here are the docs for the latest version of receptor: https://receptor.readthedocs.io/en/latest/
Hopefully this helps out. I'm going to go ahead and close this issue since it's not a bug or feature issue.
Also, a quick plug for the AWX mailing list: https://groups.google.com/g/awx-project

**Closed as completed by rebeccahhh** 2022-02-11 18:20 UTC
Labels: needs_triage

**Comment by whoamiUNIX** [comment] 2022-02-11 19:59
@rebeccahhh I’m not really happy that you close this issue. I think for community would be great to know how this can be implemented with operator configuration. I assume documentation can be improved. Link which you provided is genaral information about receptor. This sounds as lazy answer to close the issue.

**Comment by shanemcd** [comment] 2022-02-11 21:57
@whoamiUNIX your request is the same as https://github.com/ansible/awx-operator/issues/634. I see you have already commented there, so I'm not sure why you opened this. When work begins on that item you will see updates on that issue.

**Comment by shanemcd** [comment] 2022-02-11 22:01
Also, calling a maintainer of a OSS project lazy is not going to incentivize anyone to help you.
