### ISSUE TITLE
Add ability to specify labels for "default" AWX template

### ISSUE THREAD

**Issue by hagaram** [ansible/tower-operator#1820] opened 2024-04-11 07:20 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

At the moment there is possibility to specify additional_labels for child  objects of AWX object, which si neat, but if someone want to use this functionality with default helm awx template, there is no way to specify labels  for the AWX object itself (https://github.com/ansible/awx-operator/blob/devel/.helm/starter/templates/awx-deploy.yaml). 
Or at least I dont know how, so I've used kustomize to patch the object. This could be easily avoided.

If no labels are specified for AWX object, then `additional_labels` are not being applied.

**Please add ability to specify labels, when using default AWX deploy template**.

**Comment by fosterseth** [comment] 2024-04-12 17:21
thanks for opening this ticket.

would it just be a matter of adding a label here https://github.com/fosterseth/awx-operator/blob/368f78624470bf10d4c7b48a7a955242ae76c537/.helm/starter/templates/awx-deploy.yaml#L6
? then `additional_labels` will take effect?

**Comment by hagaram** [comment] 2024-05-21 12:25
@fosterseth  Thank you for commenting.
Yes, thats exactly it. This is simple kustomize patch I use, which gets the job done.
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  labels:
    external-dns.alpha.kubernetes.io/managed: true
```

So adding value, which would get passed to template metadata.labels should be enough.

**Comment by oraNod** [comment] 2024-09-04 18:33
Hi @hagaram 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:33 UTC
Labels: needs_triage, community, Helm
