### ISSUE TITLE
Issue with parsing LDAP parameters within helm values deployment for AWX operator helm chart

### ISSUE THREAD

**Issue by aldevops007** [ansible/tower-operator#1894] opened 2024-06-07 07:39 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

There is in issue with parsing LDAP parameters within helm values deployment for AWX operator helm chart for AUTH_LDAP_USER_SEARCH and AUTH_LDAP_GROUP_SEARCH parameters. In AWX UI code format for such values should be in the following brackets: '[]'. If I'm adding proper configuration for AUTH_LDAP_USER_SEARCH and AUTH_LDAP_GROUP_SEARCH parameters within helm and trying to deploy it, then after deployment in AWX UI in LDAP configuration for those values I see just '[]'. Looks like there is in issue with parsing that don't make applying values for AWX UI LDAP configuration within helm deployment. 

Additionally I checked configmap for AWX in my EKS cluster and it shows that values for  AUTH_LDAP_USER_SEARCH and AUTH_LDAP_GROUP_SEARCH parameters are in place, but format there is wrong, were added additional symbols within deployment procedure automatically that are not expected there. 

I used the following helm values for AUTH_LDAP_USER_SEARCH and AUTH_LDAP_GROUP_SEARCH parameters: 
``` 
 - setting: AUTH_LDAP_USER_SEARCH
     value:
          - "OU=Users,OU=xxxxx,OU=xxxx,DC=xxx,DC=xxxxxxxx,DC=xxxx"
          - "SCOPE_SUBTREE"
          - "(&(objectClass=user)(samAccountName=%(user)s))"

  - setting: AUTH_LDAP_GROUP_SEARCH
     value: 
          - "OU=xxxx,OU=xxxxxx,DC=xxxxxx,DC=xxxx"
          - "SCOPE_SUBTREE"
          - "(objectClass=group)"
```
In my configmap   `awx-awx-configmap` for AWX operator after deployment I got the following values: 

```
AUTH_LDAP_USER_SEARCH = ['"OU=Users,OU=xxxxx,OU=xxxx,DC=xxx,DC=xxxxxxxx,DC=xxxx"', '"SCOPE_SUBTREE"', '"(&(objectClass=user)(samAccountName=%(user)s))"']
AUTH_LDAP_GROUP_SEARCH = ['"OU=xxxx,OU=xxxxxx,DC=xxxxxx,DC=xxxx"', '"SCOPE_SUBTREE"', '"(objectClass=group)"']
```
And AWX UI I have both of those fields empty after such helm deployment: 
<img width="1228" alt="SCR-20240607-ivcy" src="https://github.com/ansible/awx-operator/assets/172015454/cc7bb8a0-bc9b-4093-bb4b-f33a90412637">

I tried many different combinations with specifying AUTH_LDAP_GROUP_SEARCH and AUTH_LDAP_USER_SEARCH parameters, but nothing is work and also is not applied for AWX UI. 

### AWX Operator version

2.18.0

### AWX version

2.18.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29

### Modifications

no

### Steps to reproduce

use such helm command for helm deployment:
```
helm upgrade --install awx-operator awx-operator/awx-operator --version 2.18.0 -n awx  -f awx-configuration/awx-helm-values-resources11.yaml
```
where `awx-helm-values-resources11.yaml` is my file with custom parameters for deploying LDAP configuration. And inside this file is necessary to insert the following:
```
AWX:
  enabled: true
  name: awx
  spec:
    extra_settings: 
          - setting: AUTH_LDAP_USER_SEARCH
             value:
                 - "OU=Users,OU=xxxxx,OU=xxxx,DC=xxx,DC=xxxxxxxx,DC=xxxx"
                 - "SCOPE_SUBTREE"
                 - "(&(objectClass=user)(samAccountName=%(user)s))"

         - setting: AUTH_LDAP_GROUP_SEARCH
            value: 
                - "OU=xxxx,OU=xxxxxx,DC=xxxxxx,DC=xxxx"
                - "SCOPE_SUBTREE"
                - "(objectClass=group)"

### Expected results

Is correct parsing of helm values and receiving related LDAP configuration in AWX UI for such parameters as: AUTH_LDAP_GROUP_SEARCH and AUTH_LDAP_USER_SEARCH 

### Actual results

I mentioned all above

### Additional information

_No response_

### Operator Logs

_No response_

**Comment by oraNod** [comment] 2024-09-04 18:32
Hi @aldevops007 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:32 UTC
Labels: needs_triage, community, Helm
