### ISSUE TITLE
imports for LDAP Group Types missing in settings.py

### ISSUE THREAD

**Issue by om22** [ansible/tower-operator#925] opened 2022-05-19 10:23 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If using anything else than the default value for LDAP Group Type, awx won't start. awx-manage migrate will throw an error that it can't find the group type. I think the python imports for the other group types are missing in /etc/tower/settings.py

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.21.0
* Kubernetes version: v1.22.5+a36406b
* AWX install method: openshift

##### STEPS TO REPRODUCE

Deploy an AWX instance including the following extra_setting:

```yaml
extra_settings:
    - setting: AUTH_LDAP_GROUP_TYPE
      value: 'GroupOfUniqueNamesType()'
```

##### EXPECTED RESULTS

AWX deploying, Setting is adjusted

##### ACTUAL RESULTS

Migration loop. When calling awx-manage from awx-task container manually:

```
sh-5.1$ awx-manage
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 147, in manage
    prepare_env()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 102, in prepare_env
    if not settings.DEBUG:  # pragma: no cover
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/settings/production.py", line 74, in <module>
    include(settings_file, optional(settings_files), scope=locals())
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/split_settings/tools.py", line 107, in include
    exec(compiled_code, scope)  # noqa: S102, WPS421
  File "/etc/tower/settings.py", line 94, in <module>
    AUTH_LDAP_GROUP_TYPE = GroupOfUniqueNamesType()
NameError: name 'GroupOfUniqueNamesType' is not defined
```

**Comment by AlanCoding** [comment] 2022-05-19 16:09
Going to close as a duplicate of https://github.com/ansible/awx-operator/issues/773

The `extra_settings` value needs to inject it as a string, but it's put in as pure python. You could try wrapping it with `"`.

**Closed as not planned by AlanCoding** 2022-05-19 16:09 UTC
Labels: needs_triage

**Comment by AlanCoding** [comment] 2022-05-19 16:10
See example in https://github.com/ansible/awx/issues/11222#issuecomment-939782609

**Comment by Colonel-Colt** [comment] 2022-06-06 07:15
Even if you wrap with `"`, this cannot be fixed. 

> See example in [ansible/awx#11222 (comment)](https://github.com/ansible/awx/issues/11222#issuecomment-939782609)

If you wrap with `"`, you will have this in /etc/tower/settings.py

`AUTH_LDAP_GROUP_TYPE = "GroupOfUniqueNamesType"`

Then, you will get an error of expected GroupType but got string. This is caused by not importing GroupOfUniqueNamesType from django_auth_ldap.config in /etc/tower/settings.py

**Comment by AlanCoding** [comment] 2022-06-08 13:05
I see. It sounds like what you need in that case is the ability to add arbitrary lines to your settings file. We can't predict everything a user might need. The [settings template](https://github.com/ansible/awx-operator/blob/e6a473b76592cc55c6d2efff88da99123b689e9e/roles/installer/templates/config.yaml.j2) does not right now seem to have anything that would suffice for that, so maybe that would be a valid RFE.
