### ISSUE TITLE
Init:CrashLoopBackOff due to chmod/chgrp on init container

### ISSUE THREAD

**Issue by mateuszdrab** [ansible/tower-operator#1093] opened 2022-10-19 19:55 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Init container fails due to attempted chmod/chgrp on the `/var/lib/awx/projects` directory

The volume is provided by Longhorn

This behavior is new since 0.27.0 (last version of the operator used that worked fine)

### AWX Operator version

0.30.0

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s 1.24.4

### Modifications

no

### Steps to reproduce

- Install k3s
- Install longhorn
- Deploy AWX instance based on longhorn volume

### Expected results

AWX starts without errors

### Actual results

AWX startup fails

### Operator Logs

The following logged by the init container
```
chmod: changing permissions of '/var/lib/awx/projects': Operation not permitted
chgrp: changing group of '/var/lib/awx/projects': Operation not permitted
```

**Comment by kurokobo** [comment] 2022-10-19 21:55
Hi, this seems to be a duplicate of #1055

**Comment by mateuszdrab** [comment] 2022-10-19 21:58
> Hi, this seems to be a duplicate of #1055

Apparently, the other issue was due to image pull backoff.

**Comment by mateuszdrab** [comment] 2022-10-19 22:03
> Hi, this seems to be a duplicate of #1055

Sorry, seemed like GitHub issue search is a hit and miss. Potentially due to the other issues title

**Closed as completed** 2022-10-19 22:03 UTC
Labels: needs_triage
