### ISSUE TITLE
Fails to update AWX from 18.0.0 to 19.0.0

### ISSUE THREAD

**Issue by OneHappyForever** [ansible/tower-operator#193] opened 2021-04-08 13:43 UTC
I am trying to update AWX to the latest version, 19.0.0. I already have AWX-operator version 0.8.0.

I've edited the my-awx.yml file to add the version like so:

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_image: quay.io/ansible/awx:19.0.0
  tower_image_pull_policy: Always

Then I run: minikube kubectl -- apply -f my-awx.yml

However, it does not restart the pods. It says changed, but it's still version 18.0.0. I checked the logs from within awx-operator, and ansible has an error:

TASK [installer : Create Database if no database is specified] *****************\r\ntask path: /opt/ansible/roles/installer/tasks/database_configuration.yml:67\nfatal: [localhost]: FAILED! => {\"changed\": false, \"error\": 422, \"msg\": \"Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"StatefulSet.apps \\\\\\\\\\\"awx-postgres\\\\\\\\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than \\\\'replicas\\\\', \\\\'template\\\\', and \\\\'updateStrategy\\\\' are forbidden\\\",\\\"reason\\\":\\\"Invalid\\\",\\\"details\\\":{\\\"name\\\":\\\"awx-postgres\\\",\\\"group\\\":\\\"apps\\\",\\\"kind\\\":\\\"StatefulSet\\\",\\\"causes\\\":[{\\\"reason\\\":\\\"FieldValueForbidden\\\",\\\"message\\\":\\\"Forbidden: updates to statefulset spec for fields other than \\\\'replicas\\\\', \\\\'template\\\\', and \\\\'updateStrategy\\\\' are forbidden\\\",\\\"field\\\":\\\"spec\\\"}]},\\\"code\\\":422}\\\\n'\", \"reason\": \"Unprocessable Entity\", \"status\": 422}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=23   changed=0    unreachable=0    failed=1    skipped=15   rescued=0    ignored=0   \r\n\n","job":"261049867304784443","name":"awx","namespace":"default","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:239"}

{"level":"error","ts":1617888828.2578466,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}

As for postgresql, this is what I get via kubectl describe pods:

Events:
  Type     Reason          Age                From     Message
  ----     ------          ----               ----     -------
  Warning  FailedMount     51m                kubelet  Unable to attach or mount volumes: unmounted volumes=[default-token-gb2cb postgres], unattached volumes=[default-token-gb2cb postgres]: error processing PVC default/postgres-awx-postgres-0: failed to fetch PVC from API server: persistentvolumeclaims "postgres-awx-postgres-0" is forbidden: User "system:node:minikube" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "default": no relationship found between node 'minikube' and this object
  Warning  FailedMount     51m (x2 over 51m)  kubelet  MountVolume.SetUp failed for volume "default-token-gb2cb" : failed to sync secret cache: timed out waiting for the condition
  Normal   SandboxChanged  51m                kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          51m                kubelet  Container image "postgres:12" already present on machine
  Normal   Created         51m                kubelet  Created container postgres
  Normal   Started         51m                kubelet  Started container postgres
  Normal   SandboxChanged  18m                kubelet  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          18m                kubelet  Container image "postgres:12" already present on machine
  Normal   Created         18m                kubelet  Created container postgres
  Normal   Started         18m                kubelet  Started container postgres

However, when I check awx in the browser, all the data is there, showing that postgresql is working.

Is there something I'm missing?

EDIT: Also, when I type minikube kubectl edit awx...../awx it shows the variable tower_image: quay.io/ansible/awx:19.0.0  so it means the variable was added correctly and was recognized. But the status shows it as 18.0.0 still

**Comment by shanemcd** [comment] 2021-04-08 13:45
Dupe of https://github.com/ansible/awx-operator/issues/163. See that issue for workaround.

**Closed as completed** 2021-04-08 14:22 UTC

**Comment by Commifreak** [comment] 2021-04-30 07:51
Re-applying the my-awx is enough? What about the operator upgrade from 0.7.0 to 0.8.0?
