### ISSUE TITLE
allow extra settings values to come from Kubernetes secrets

### ISSUE THREAD

**Issue by tylergmuir** [ansible/tower-operator#1666] opened 2023-12-12 22:11 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

There should be an option to allow the values of `extra_settings` to be populated from Kubernetes secrets. There are some values that can be set but are sensitive and this would provide a way to still bootstrap those values while compromising security of the values when the yaml file is stored in git.

**Comment by kurokobo** [comment] 2023-12-13 15:35
Duplicate of: https://github.com/ansible/awx-operator/issues/1224

My workaround also there: https://github.com/ansible/awx-operator/issues/1224#issuecomment-1772270271

**Comment by djyasin** [comment] 2023-12-13 18:09
Since this is a duplicate issue, and there's already work being done around the original issue, we will close this one.

**Closed as completed by djyasin** 2023-12-13 18:09 UTC
Labels: needs_triage, community
