### ISSUE TITLE
Unable to sync git project from a self hosted gitlab via ssh

### ISSUE THREAD

**Issue by craph** [ansible/tower-operator#725] opened 2022-01-11 07:55 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

After installing AWX with AWX operator and importing old database from awx 17.x, I'm unable to sync my projects from a self hosted Gitlab server via SSH clone.

##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: 0.10.0
* Kubernetes version: 1.20.11
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

##### STEPS TO REPRODUCE

create a new project with a source control url like this : `ssh://git@your_git_server:your_custom_port/some_group/my_project.git` and add source control credential. In my case it's a user with a private ssh key.
Then save it and try to sync.

##### EXPECTED RESULTS

The sync should work.

##### ACTUAL RESULTS

The sync is still running indefinitly ... In AWX 17.x the same project sync correctly
Where can I see the log of the sync process to investigate more ?

##### AWX-OPERATOR LOGS
the only logs I can find is in the awx-tasks container in the job_lifecycle.log
```bash
{"type": "projectupdate", "task_id": 2791, "state": "running_playbook", "template_name": "my-project", "guid": "1e632d939b7f4b649d51641d18d66264", "time": "2022-01-11T07:31:28.279033+00:00"}
```

**Comment by WebSpider** [comment] 2022-01-19 18:52
Have you tried using 'git@your_git_server:your_custom_port/some_group.git` as the URL?

**Comment by shanemcd** [comment] 2022-01-31 18:34
Are you using crowdstrike? _Possibly_ a dupe of https://github.com/ansible/awx/issues/11518

**Comment by shanemcd** [comment] 2022-01-31 18:35
Oops. That is you 😄. Closing this in favor of that issue.

**Closed as completed by shanemcd** 2022-01-31 18:35 UTC
Labels: needs_triage
