### ISSUE TITLE
Cannot update execution environment version in place

### ISSUE THREAD

**Issue by daenney** [ansible/tower-operator#256] opened 2021-04-29 12:06 UTC
I have this:

```yaml
  tower_ee_images:
  - image: my-env:v0.1.1
    name: my-env
```

I wanted to update to v0.1.2, so I updated the image. The operator caught on, pods restarted but when going into AWX -> Execution Environments I still see the "my-env" environment using the v0.1.1 tag

**Comment by tchellomello** [comment] 2021-04-30 03:57
@daenney  could you please elaborate and provide some command outputs from the steps you have taken?  Interested in seeing a pattern to reproduce the same issue. Thanks!

**Comment by daenney** [comment] 2021-04-30 09:59
I did: `kubectl edit awx/awx` and changed the version of the `image` key without changing the `name`. I waited for the operator to kick in and for the new AWX pods to be started. After that, I navigated to the Execution Environments in the AWX UI and noticed that the EE was still pointing at the old image tag.

**Comment by tchellomello** [comment] 2021-05-11 03:15
@daenney  I just tested it on the latest `devel` and worked for me. 

```sh
# kubectl edit awx awx-demo-devel
....
spec:
  tower_ee_images:
    - image: registry.tatu.home/ansible/awx-ee:0.1.0
      name: ee-010
    - image: registry.tatu.home/ansible/awx-ee:0.2.0
      name: ee-020
```

Then this was the result:

![image](https://user-images.githubusercontent.com/809840/117752883-90ce5300-b1e5-11eb-8088-366929d092ee.png)

Please try again with the latest `devel` which should work for you. Please let us know the results.

**Comment by daenney** [comment] 2021-05-11 09:21
Did you try to update one in-place? Like change the tag that `ee-020` points at to awx-ee:0.2.1` for example? Right now your config suggests you have 2 execution environments. That works for me too. The problem I'm having is using a generic name, without a version identifier in it, and only updating the image tag (so I don't have to go around AWX and update which execution environment is used every time).

So imagine you have this first:

```yaml
spec:
  tower_ee_images:
    - image: registry.tatu.home/ansible/awx-ee:0.1.0
      name: My Custom Execution Environment
```

And then update it to this:
```yaml
spec:
  tower_ee_images:
    - image: registry.tatu.home/ansible/awx-ee:0.2.0
      name: My Custom Execution Environment
```

That doesn't seem to work for me. I'll give it a go on devel.

**Comment by tchellomello** [comment] 2021-05-11 15:55
Before:
![image](https://user-images.githubusercontent.com/809840/117844254-85af0d80-b24d-11eb-9fab-ea39d54a1741.png)
```yaml
        image: registry.tatu.home/ansible/awx-ee:0.1.0
        imagePullPolicy: IfNotPresent
        name: awx-devel-ee-ee
```

Then modified, new deployment rolled out

```yaml
awx-devel-ee-c5f7b4479-jd25d                               0/4     Pending     0          0s
awx-devel-ee-c5f7b4479-jd25d                               0/4     Pending     0          0s
awx-devel-ee-c5f7b4479-jd25d                               0/4     ContainerCreating   0          0s
awx-devel-ee-c5f7b4479-jd25d                               4/4     Running             0          2s
awx-devel-ee-66588d9f74-wwm8w                              4/4     Terminating         0          18m
awx-devel-ee-66588d9f74-wwm8w                              0/4     Terminating         0          18m
awx-devel-ee-66588d9f74-wwm8w                              0/4     Terminating         0          19m
awx-devel-ee-66588d9f74-wwm8w                              0/4     Terminating         0          19m

-- deployment got updated
- args:
        - receptor
        - --config
        - /etc/receptor.conf
        image: registry.tatu.home/ansible/awx-ee:0.2.0
        imagePullPolicy: IfNotPresent
        name: awx-devel-ee-ee
```

![image](https://user-images.githubusercontent.com/809840/117844828-0110bf00-b24e-11eb-9b84-f0cd63cbe469.png)

Looking at the database, it still points to the old one:

```sql
awx=# select * from main_executionenvironment;
 id |    created    |   modified    | description |     image      | managed_by_tower | created_by_id | credential_id | modified_by_id | organization_id |      name      | pull 
----+---------------+---------------+-------------+----------------+------------------+---------------+---------------+----------------+-----------------+----------------+------
  1 | 2021-05-11 15.| 2021-05-11 15.|             | registry.tatu..| t                |             1 |               |              1 |                 | My Custom Exec.| 
    |.:24:02.674302.|.:24:02.674327.|             |.home/ansible/a.|                  |               |               |                |                 |.ution Environm.| 
    |.+00           |.+00           |             |.wx-ee:0.1.0    |                  |               |               |                |                 |.ent            | 
(1 row)
```

Then checking the `DEFAILT_EXECUTION_ENVIRONMENTS`, it was updated as expected:

```yaml
kubectl iexec awx-devel-ee /bin/bash                                                                                                                                 11:50:05
Namespace: default | Pod: ✔ awx-devel-ee-c5f7b4479-jd25d
Container: ✔ awx-devel-ee-web
bash-4.4$ cat /etc/tower/conf.d/execution_environments.py 
DEFAULT_EXECUTION_ENVIRONMENTS = [
    {'name': 'My Custom Execution Environment' , 'image': 'registry.tatu.home/ansible/awx-ee:0.2.0'},
]
```

So the problem is really at https://github.com/ansible/awx/blob/devel/awx/main/management/commands/create_preload_data.py#L71-L76 which requires the name to be different so the data will be updated, otherwise, it will consider the object is already stored. 

```python
                for ee in reversed(settings.DEFAULT_EXECUTION_ENVIRONMENTS):
                    _, created = ExecutionEnvironment.objects.get_or_create(name=ee['name'], defaults={'image': ee['image'], 'managed_by_tower': True})

                if created:
                    changed = True
                    print('Default Execution Environment(s) registered.')
```

Is it something we should update @shanemcd  @matburt ?

**Comment by shanemcd** [comment] 2021-05-13 15:06
We might want to consider updating the image value in this case, in the AWX code where you just linked to.

**Comment by tchellomello** [comment] 2021-05-13 19:34
> We might want to consider updating the image value in this case, in the AWX code where you just linked to.

I'll work on a patch then. Thanks!

**Comment by tchellomello** [comment] 2021-05-19 01:40
Closing as PR https://github.com/ansible/awx/pull/10206 was merged on AWX 

It will be present on the next AWX version.

**Closed as completed by tchellomello** 2021-05-19 01:40 UTC
Labels: type:bug
