### ISSUE TITLE
failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.3.tgz : 404 Not Found

### ISSUE THREAD

**Issue by vovan42002** [ansible/tower-operator#1200] opened 2023-01-25 14:12 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'm trying to install awx-operator via helm install

`helm install --dry-run my-awx-operator awx-operator/awx-operator --version 1.1.3`
`Error: INSTALLATION FAILED: failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.3.tgz : 404 Not Found`

But there is a 404 not found error. It happened for the first time on January 25. As early as January 24, the installation was successful. I think that this may be related to the release of the new version 1.1.4 (it has the same error). Maybe something was broken during the release of the new version.

### AWX Operator version

1.1.3

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.25

### Modifications

no

### Steps to reproduce

Run command `helm install`.
`helm install my-awx-operator awx-operator/awx-operator --version 1.1.3` or
`helm install my-awx-operator awx-operator/awx-operator --version 1.1.4`

### Expected results

awx-operator should be installed, or at least crashed with another error

### Actual results

Can't fetch chart from remote repo
`Error: INSTALLATION FAILED: failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.3.tgz : 404 Not Found`

**Comment by Binker** [comment] 2023-01-25 14:42
Applies to every version.

`helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "awx-operator" chart repository
Update Complete. ⎈Happy Helming!⎈`
`helm repo list
NAME            URL                                    
awx-operator    https://ansible.github.io/awx-operator/`
`helm install -n awx --create-namespace awx-operator awx-operator/awx-operator
Error: INSTALLATION FAILED: failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz : 404 Not Found`

Shot in the dark, wild quess, call it what you will, but could this have something to do with it? https://github.com/ansible/awx-operator/commit/ac5a2538bc345a3f71feccdce526a45543565ccd

**Comment by yurenkov** [comment] 2023-01-26 03:24
Also faced with this problem.
To the gh-pages branches in the index.yaml all links have the form:
https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz
The correct link at the same time:
https://github.com/ansible/awx-operator/releases/download/1.1.4/awx-operator-1.1.4.tgz

**Comment by GlennHD** [comment] 2023-01-26 05:38
Manual helm fix for those testing now. Based on everyone else's inputs. Thank you!
```zsh
helm env | grep HELM_REPOSITORY_CACHE 				### find the repo ###
nano ./awx-operator-index.yaml					### edit the awx index in the repo ###
```
```zsh
### replace the URL. ###
entries:
  awx-operator:
  - apiVersion: v2
    urls:
#    - https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz
    - https://github.com/ansible/awx-operator/releases/download/1.1.4/awx-operator-1.1.4.tgz
```
```zsh
### press on ###
helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
```

**Comment by blueprismo** [comment] 2023-01-26 09:07
Instead of changind the Helm cache, you can also install it directly through the URL (and to another version!!!)
```sh
helm install -n awx --create-namespace awx-operator https://github.com/ansible/awx-operator/releases/download/1.1.3/awx-operator-1.1.3.tgz --wait
```

**Comment by Binker** [comment] 2023-01-26 09:17
Can confirm that the workaround provided by @GlennHD is good.
Apparently what's generating ./awx-operator-index.yaml is broken.

**Comment by janorn** [comment] 2023-01-27 12:23
@miles-w-3 this url is incorrect in the Makefile.
https://github.com/ansible/awx-operator/blob/c1b2e73123bc58f1e92a098780c7666a50e734fd/Makefile#L394
Should be the same as used for downloading the tar files 
https://github.com/ansible/awx-operator/blob/c1b2e73123bc58f1e92a098780c7666a50e734fd/Makefile#L378

**Comment by janorn** [comment] 2023-01-27 13:31
If you need you can use this URL as repo. The helm chart there is a fixed version pointing to the awx-operator releases.

https://janorn.github.io/helmrepo-awx/

**Comment by vovan42002** [comment] 2023-01-27 13:35
> If you need you can use this URL as repo. The helm chart there is a fixed version pointing to the awx-operator releases.
> 
> https://janorn.github.io/helmrepo-awx/

@janorn is this just a temporary repo?

**Comment by janorn** [comment] 2023-01-27 13:40
> > If you need you can use this URL as repo. The helm chart there is a fixed version pointing to the awx-operator releases.
> > https://janorn.github.io/helmrepo-awx/
> 
> @janorn is this just a temporary repo?

Its my personal repo so it is manually updated when needed. Use it until the official work. But I will not remove it. However when the official is working I probably wont update it anymore 😄

**Comment by miles-w-3** [comment] 2023-01-27 13:44
@janorn i recommend reaching out to @rooftopcellist or @TheRealHaoLiu, I have limitations in my testing environment but I believe they can validate the url and push a change up to index.yaml

**Comment by janorn** [comment] 2023-01-27 13:50
@miles-w-3 I think the issue is with the helm index command. It takes a dir and applies same URL to all files. To solve this we probably will need to move the helm index into the previous loop and run it multiple times with just one file and a uniq URL for each file.

**Comment by janorn** [comment] 2023-01-27 14:00
I think this can be easily fixed with putting the tar files in subdirs and change the URL to the correct one. I will make a PR.

**Closed as completed** 2023-01-27 14:32 UTC
Labels: needs_triage, community
