### ISSUE TITLE
Folder /var/lib/awx/public doesn't get created

### ISSUE THREAD

**Issue by iohenkies** [ansible/tower-operator#461] opened 2021-07-08 06:38 UTC
Hi all,

I must be doing something wrong, hope you can help. We're running on Kubernetes 1.20.7 on AKS. I've tried operator 0.11.0 and 0.12.0. I'm trying to get a basic install going and I've followed the documentation almost* exactly:
https://github.com/ansible/awx-operator

\* The only thing I changed is the namespace.

Operator and all resources get created successfully in the specified namespace. I then create a AWX deployment using the simple example given in said documentation or a little bit modified to use persistent storage:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-instance
  namespace: infra-awx
spec:
  service_type: ClusterIP
  hostname: awx.cloud.mydomain.com
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: awx-static-data
```

Applying this yaml (plus an Ingress and PVC yaml), all resources again get created successfully in my desired namespace. Pods are running, persistent storage gets created in Azure, PVC are bound, etc. Surfing to our URL it hits the `awx-instance` just fine, but the problem seems to lie in the /var/lib/awx/public not getting created:

```
10.15.0.6 - - [08/Jul/2021:06:29:13 +0000] "GET /static/js/runtime-main.26b25ec7.js HTTP/1.1" 404 162 "http://awx.cloud.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "84.105.157.54:58779"
2021/07/08 06:29:13 [error] 22#0: *7546 open() "/var/lib/awx/public/static/css/2.939a7c04.chunk.css" failed (2: No such file or directory), client: 10.15.0.5, server: _, request: "GET /static/css/2.939a7c04.chunk.css HTTP/1.1", host: "awx.cloud.mydomain.com", referrer: "http://awx.cloud.mydomain.com/"
10.15.0.5 - - [08/Jul/2021:06:29:13 +0000] "GET /static/css/2.939a7c04.chunk.css HTTP/1.1" 404 162 "http://awx.cloud.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "84.105.157.54:58778"
2021/07/08 06:29:13 [error] 22#0: *7546 open() "/var/lib/awx/public/static/js/main.5c06d07f.chunk.js" failed (2: No such file or directory), client: 10.15.0.5, server: _, request: "GET /static/js/main.5c06d07f.chunk.js HTTP/1.1", host: "awx.cloud.mydomain.com", referrer: "http://awx.cloud.mydomain.com/"
10.15.0.5 - - [08/Jul/2021:06:29:13 +0000] "GET /static/js/main.5c06d07f.chunk.js HTTP/1.1" 404 162 "http://awx.cloud.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "84.105.157.54:58778"
2021/07/08 06:29:13 [error] 22#0: *7547 open() "/var/lib/awx/public/static/js/2.81f36753.chunk.js" failed (2: No such file or directory), client: 10.15.0.5, server: _, request: "GET /static/js/2.81f36753.chunk.js HTTP/1.1", host: "awx.cloud.mydomain.com", referrer: "http://awx.cloud.mydomain.com/"
10.15.0.5 - - [08/Jul/2021:06:29:13 +0000] "GET /static/js/2.81f36753.chunk.js HTTP/1.1" 404 162 "http://awx.cloud.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "84.105.157.54:58780"
10.15.0.5 - - [08/Jul/2021:06:29:13 +0000] "GET /static/js/2.81f36753.chunk.js HTTP/1.1" 404 162 "http://awx.cloud.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0" "84.105.157.54:58778"
2021/07/08 06:29:13 [error] 22#0: *7547 open() "/var/lib/awx/public/static/js/2.81f36753.chunk.js" failed (2: No such file or directory), client: 10.15.0.5, server: _, request: "GET /static/js/2.81f36753.chunk.js HTTP/1.1", host: "awx.cloud.mydomain.com", referrer: "http://awx.cloud.mydomain.com/"
2021/07/08 06:29:13 [error] 22#0: *7547 open() "/var/lib/awx/public/static/js/main.5c06d07f.chunk.js" failed (2: No such file or directory), client: 10.15.0.5, server: _, request: "GET /static/js/main.5c06d07f.chunk.js HTTP/1.1", host: "awx.cloud.mydomain.com", referrer: "http://awx.cloud.mydomain.com/"
```

Resulting in me getting only a blank page. Surfing to http://awx.cloud.mydomain.com/api/ gets me to the root of the rest API (without proper formatting it seems).

When I deploy without persistent storage the `public` folder doesn't get created, when I deploy with persistent storage the contents don't get created.

I of course did a lot of searching around already, where I for instance stumbled on this blog and a tip in the comments to run `/usr/bin/launch_awx.sh` from the container:
https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/

Problem with this is that the pod runs as non root and I don't have the correct privileges. This are the contents of `/var/lib/awx`. Public and projects are empty.

```
bash-4.4$ ls -al
total 36
drwxrwxr-x 1 root root 4096 Jul  7 14:46 .
drwxr-xr-x 1 root root 4096 Jun 17 19:37 ..
prw------- 1 awx  root    0 Jul  7 14:45 awxfifo
-rw-r--r-- 1 awx  root   40 Jul  7 14:46 .configsha
drwxr-xr-x 3 root root 4096 Jun 17 19:37 .local
drwxr-xr-x 3 root root 4096 Jul  7 14:44 projects
drwxr-xr-x 3 root root 4096 Jul  7 14:44 public
drwxrwxrwx 2 root root 4096 Jul  7 14:47 rsyslog
drwxr-xr-x 3 root root 4096 Jun 17 19:24 venv
```

What am I missing here?

**Comment by iohenkies** [comment] 2021-07-08 06:48
This is probably the same problem https://github.com/ansible/awx-operator/issues/357

But for me doesn't explain why without persistent volumes I seem to hit the same issue and I don't understand how I can solve this in a non-dev environment.

**Comment by iohenkies** [comment] 2021-07-08 06:57
Yes, editing the security context as described in the linked article works, but I would of course like to not do that :)
```
      securityContext:
        fsGroup: 1000
```
(Because this deployment gets of course created by the operator)

**Comment by shanemcd** [comment] 2021-07-09 17:21
Closing as a dupe of https://github.com/ansible/awx-operator/issues/357

**Closed as completed by shanemcd** 2021-07-09 17:21 UTC
Labels: component:operator
