### ISSUE TITLE
2.13.1 web and task won't install

### ISSUE THREAD

**Issue by ma-gokbas** [ansible/tower-operator#1771] opened 2024-03-14 06:36 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am using external postgresql. I download https://github.com/ansible/awx-operator/blob/devel/.helm/starter/values.yaml file to install with helm and change false values to true. Only awx-operator-controller-manager is installed. awx-web is not installed although I make awx enable true. awx-service endpoint equivalents are empty.

I do the installation as follows.

helm install awx-operator awx-operator/awx-operator -n awx -f values.yaml

file content:
AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    admin_user: admin

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: postgresql-ha-pgpool.db.svc.cluster.local
    port: 5432
    dbName: awx
    username: awx
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: mypassword
    sslmode: prefer
    type: unmanaged

### AWX Operator version

2.13.1

### AWX version

v24.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.28.1

### Modifications

no

### Steps to reproduce

-

### Expected results

-

### Actual results

-

### Additional information

-

### Operator Logs

-

**Comment by kurokobo** [comment] 2024-03-14 06:48
Could you please gather logs from AWX Operator?

**Comment by ma-gokbas** [comment] 2024-03-14 07:08
> Could you please gather logs from AWX Operator?

[awx-manager.log.zip](https://github.com/ansible/awx-operator/files/14598148/awx-manager.log.zip)

**Comment by kurokobo** [comment] 2024-03-14 07:18
@ma-gokbas 
Thanks, 

>  TASK [Apply deployment resources] ******************************** 
> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'web_liveness_period' is undefined.

Seems your cluster has old CRDs that not supports latest Operator (the latest CRD has `web_liveness_period` which defaults to `0`). 

Refer to the "[Caveats on upgrading existing installation](https://github.com/ansible/awx-operator/tree/devel/.helm/starter#caveats-on-upgrading-existing-installation)" and try to apply CRD changes.

```bash
kubectl apply --server-side --force-conflicts -k github.com/ansible/awx-operator/config/crd?ref=2.13.1
```

**Comment by ma-gokbas** [comment] 2024-03-14 07:40
> @ma-gokbas Thanks,
> 
> > TASK [Apply deployment resources] ********************************
> > fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'web_liveness_period' is undefined.
> 
> Seems your cluster has old CRDs that not supports latest Operator (the latest CRD has `web_liveness_period` which defaults to `0`).
> 
> Refer to the "[Caveats on upgrading existing installation](https://github.com/ansible/awx-operator/tree/devel/.helm/starter#caveats-on-upgrading-existing-installation)" and try to apply CRD changes.
> 
> ```shell
> kubectl apply --server-side --force-conflicts -k github.com/ansible/awx-operator/config/crd?ref=2.13.1
> ```

Hello,

Thank you for your reply. Exactly as you said. It loaded when I deleted the old CRD records.

**Comment by AKK90** [comment] 2024-03-14 07:50
@ma-gokbas hocam selamlar,

Aynı sorun ile sabah bende karşılaştım,fakat bizim yapıda Awx, OpenShift üzerinde kurulu.Yukarıda ki komutu girdim fakat değişen bişey olmadı task pod'u ayağa kalkmıyor.Başka bir fikrin var mı ne yapabilirim?
Teşekkürler,

**Comment by ma-gokbas** [comment] 2024-03-14 08:04
> @ma-gokbas hocam selamlar,
> 
> Aynı sorun ile sabah bende karşılaştım,fakat bizim yapıda Awx, OpenShift üzerinde kurulu.Yukarıda ki komutu girdim fakat değişen bişey olmadı task pod'u ayağa kalkmıyor.Başka bir fikrin var mı ne yapabilirim? Teşekkürler,

Merhaba,

kubectl get crd komutunu verdiğinizde aşağıdaki kayıtları görmeniz lazım. sanırım openshift için oc get crd komutunu kullanmalısınız. bu aşağıdaki crd kayıtlarını silin. openshift crd kaydı silme dökümanlarına bakınız

awxbackups.awx.ansible.com 
awxmeshingresses.awx.ansible.com 
awxrestores.awx.ansible.com 
awxs.awx.ansible.com

**Comment by kunkanon** [comment] 2024-03-14 11:22
Hello!
I'm complicated with a topic.
When upgrading to version 2.3.1, a pod named awx-postgresql-15-0 was created
However, it was not possible to migrate data from the awx-postgresql-13-0 pod
Is it necessary to perform the dump manually?

Additionally:
The awx-task and awx-web pods are not starting.
![Captura de Tela 2024-03-14 às 08 36 11](https://github.com/ansible/awx-operator/assets/23107622/42b4cd1b-dbcb-4342-955f-4bfdda756899)

Kubernets
Client Version: v1.25.6+k3s1
Kustomize Version: v4.5.7
Server Version: v1.25.6+k3s1


Here's the log:
[operator.log.zip](https://github.com/ansible/awx-operator/files/14601416/operator.log.zip)

**Comment by TheRealHaoLiu** [comment] 2024-03-14 16:18
@kunkanon your question is not related to this issue.
check the operator log for the progress data migration from postgres 13 to postgres 15 data migration should be automatic and postgres 13 statefulset and service should be automatically deleted after the data migration

**Comment by TheRealHaoLiu** [comment] 2024-03-14 21:21
closing this because we identify the root cause 

if you are installing using helm chart you need to manually update the CRD see https://github.com/ansible/awx-operator/blob/devel/.helm/starter/README.md#caveats-on-upgrading-existing-installation for more detail

**Closed as completed by TheRealHaoLiu** 2024-03-14 21:21 UTC
Labels: needs_triage, community

**Comment by bryan-srg** [comment] 2024-03-24 23:17
Hi, I seem to be experiencing the exact same error - but mine is occuring during a brand new install to a brand new EKS cluster - so there are no out of date CRDs (at least, I don't see how there could be). Do I open a new issue, or will someone reopen this one?
