### ISSUE TITLE
File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 244, in _get_json     ret = s.get(url, params=params, verify=self.get_option('validate_certs')

### ISSUE THREAD

**Issue by birb57** [ansible/tower-operator#933] opened 2022-05-31 15:49 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

ansible-inventory [core 2.12.5.post0]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections:/usr/share/automation-controller/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.8.12 (default, Sep 21 2021, 00:10:52) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
No config file found; using defaults
setting up inventory plugins
Loading collection theforeman.foreman from /usr/share/ansible/collections/ansible_collections/theforeman/foreman
[WARNING]:  * Failed to parse /runner/inventory/foreman.yml with auto plugin:
HTTPSConnectionPool(host='10.246.0.238', port=443): Max retries exceeded with
url: /api/v2/status?page=1&per_page=250 (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1131)')))
  File "/usr/local/lib/python3.8/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.8/site-packages/ansible/plugins/inventory/auto.py", line 58, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 671, in parse
    self._populate()
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 424, in _populate
    if self._use_inventory_report():
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 379, in _use_inventory_report
    result = self._get_json(status_url)
  File "/usr/share/ansible/collections/ansible_collections/theforeman/foreman/plugins/inventory/foreman.py", line 244, in _get_json
    ret = s.get(url, params=params, verify=self.get_option('validate_certs'))
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 533, in request

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version:  0.21.0
* Kubernetes version:  1.22.7
* AWX install method: k3s

##### STEPS TO REPRODUCE

Create inventory with satellite 6.9 as source

##### EXPECTED RESULTS

List of hosts and groups and variables

##### ACTUAL RESULTS

Error in summary

##### ADDITIONAL INFORMATION

How can I set "validate_certs: false" from my ansible awx GUI ?

**Comment by birb57** [comment] 2022-06-02 10:06
Hi

To clarify error occurred when I try to run/sync a source inventory linked to Redhat Satellite 6 inventory source

thanks for your support

**Comment by sevko21** [comment] 2022-06-08 11:33
got the same error with satellite inventory and adding bundle-ca.crt

**Comment by fosterseth** [comment] 2022-06-10 17:14
I believe this is a duplicate of https://github.com/ansible/awx/issues/12345

if you think it is a different issue, then please let us know in the mailing list https://groups.google.com/g/awx-project

**Closed as completed by fosterseth** 2022-06-10 17:14 UTC
Labels: needs_triage

**Comment by solomonchu30** [comment] 2022-07-26 07:01
@birb57 > Did you successfully resolved the above issue? I am facing similar issue. Please could provide your solution.
