### ISSUE TITLE
Issue with deployment

### ISSUE THREAD

**Issue by MichaelCade** [ansible/tower-operator#824] opened 2022-03-10 14:17 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I found that with the latest version the awx-demo.yml file set with NodePort does not work with Minikube or the instructions, the pods just never get provisioned for awx-demo-*** the postgres pod is deployed and works fine. 

In order for me to get this working, I changed the NodePort to ClusterIP as we are exposing the service later on anyway through minikube ingress. This then enables the provisioning of the 4 awx-demo pods. 

I think the example in the minikube walkthrough readme.md could be changed to reflect this. 

##### ENVIRONMENT
* AWX version: [0.18.0]
* Operator version: X.Y.Z
* Kubernetes version: v1.22.2
* AWX install method: minikube

**Comment by kurokobo** [comment] 2022-03-10 14:19
Seems a duplicate of #814

**Comment by deeco** [comment] 2022-03-10 21:03
Plus one for this issue , I tried to resolve with workaround mentioned here https://github.com/ansible/awx-operator/issues/626

Also cannot seem to set the logs: no_log: true

**Comment by shatteredsword** [comment] 2022-04-25 17:16
did someone find a workaround for this? i've tried deploying on brand new systems on both ubuntu22 and fedora35 and can't get past that step on either one.

**Comment by deeco** [comment] 2022-04-25 17:20
> 

I got it to work with workaround above and applying directly as a separate manifest

**Comment by shatteredsword** [comment] 2022-04-25 18:12
so apparently all i had to do to get it to work was to follow the setup guide but change the tag number to 0.14.0 before the first deploy.
deploy it, change the number back to 0.20.0 and redeploy.

**Comment by shatteredsword** [comment] 2022-04-25 20:11
aaand they just fixed it with 0.20.1

**Closed as completed** 2022-06-10 16:06 UTC
Labels: needs_triage
