### ISSUE TITLE
AWX ee_extra_env not working

### ISSUE THREAD

**Issue by rsdoherty** [ansible/tower-operator#1948] opened 2024-08-30 22:24 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I've just deployed a very basic AWX install via helm, and I have this as my spec:

```
- name: Deploy AWX
  kubernetes.core.helm:
    name: awx
    chart_ref: awx-operator/awx-operator
    release_namespace: default
    values:
      AWX:
        enabled: true
        spec:
          ee_extra_env: |
            - name: MYCUSTOMVAR
              value: foo
```

Yet whenever the globally available EE is launched, I do not see MYCUSTOMVAR populated in the pod spec - the environment is blank.

Is this expected? I cannot seem to find a way to have the AWX crd pass environment variables to the globally available EE's.

I do see the config when I do `k get awxs -o yaml`, and as a test I set `ee_extra_volume_mounts` with no `extra_volumes` and things still worked - suggesting this isn't getting passed to the container at all.

### AWX Operator version

2.19.1

### AWX version

24.6.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29.7

### Modifications

no

### Steps to reproduce

- Deploy AWX via helm
- Add ee_extra_env (https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/exporting-environment-variables-to-containers.html)
- Run a job in that EE, and it doesn't show the environment variables as expected

### Expected results

Environment variables show in globally available EE as expected

### Actual results

Container starts with no environment set

**Comment by kurokobo** [comment] 2024-08-31 02:00
@rsdoherty 
Hi, this is expected. The _globally available EE_ means that _`awx-ee` container in `awx-task` pod_, which does not mean the EE for your automation job.
If you want to pass environment variables to your automation job pod, use `Extra Environment Variables` in `Settings` > `Job settings` on the Web GUI, or pass `AWX_TASK_ENV` to your AWX CR by `extra_settings` or `extra_settings_files`.

Alternatively you can use customized [Container Group with customized pod spec](https://docs.ansible.com/ansible-tower/latest/html/administration/external_execution_envs.html#customize-the-pod-spec).

**Comment by rsdoherty** [comment] 2024-08-31 09:36
I haven't configured any further execution environments yet:

![image](https://github.com/user-attachments/assets/5f68086c-ecf2-4ad9-addb-6d60e41c303f)

I'd have expected the `ee_extra_env` keys to show up in these?

**Comment by oraNod** [comment] 2024-09-04 18:31
Hi @rsdoherty 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:31 UTC
Labels: needs_triage, community, Helm
