### ISSUE TITLE
awx pod not creating on new k8s cluster on rhel 7

### ISSUE THREAD

**Issue by slaurencelle** [ansible/tower-operator#521] opened 2021-09-02 19:51 UTC
Hello,
I seem to have a problem deploying awx on kubernetes wich is install on rhel 7 host.
I have try with th awx-operator 0.10 to 0.13 and same result , the awx-operator is install and working
but when i push my awx install file , i have the database pod create and running but no awx pod.

i did have create my pv and pvc local-storage for the database pod and project pod (awx) to have persitent storage.
i don't have any error anywhere 
here is the 2 file i try to deploy the awx pod:

the simple one:
cat awx-deploy.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-demo.example.com

the second file : 
cat awx-deploy2.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: none
  postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 30Gi
  postgres_storage_class: local-storage
  web_resource_requirements:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  projects_persistence: true
  projects_storage_class: local-storage
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 50Gi

here is the what i have on the pvc that is suppose to be use by the awx pod
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  WaitForFirstConsumer  13s (x12 over 2m40s)  persistentvolume-controller  waiting for first consumer to be created before binding

ant the state:
kubectl get pvc
NAME                           STATUS    VOLUME        CAPACITY   ACCESS MODES   STORAGECLASS    AGE
awx-demo-projects-claim        Pending                                           local-storage   9m45s
postgres-awx-demo-postgres-0   Bound     postgres-pv   30Gi       RWX            local-storage   9m40s

here is the info in the pv and pvc file for the awx pod

cat pv2-test.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: projects-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/projects
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
          - worker2
  
pvc2-test.yml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-demo-projects-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

Hope you can help me on this one :(

Regards,

Stephane

**Comment by slaurencelle** [comment] 2021-09-02 20:17
I just try with the version 0.9.0 of the awx-operator and same result :(

regards,

Stephane

**Comment by slaurencelle** [comment] 2021-09-02 20:30
in the awx-operator pod logs i see this error : 
"job":"6842348953158377901","name":"awx-demo","namespace":"default","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:239"}
{"level":"error","ts":1630614492.9189487,"logger":"controller-runtime.controller",msg":"Reconciler error","controller":"awx-controller","request":"default/awx-demo","error":"event runner on failed","stacktrace"

Hope it can help
Stephane

**Comment by tobgen** [comment] 2021-09-03 13:22
I have the same issue. 
Worked like a charm on my pre 1.22.x cluster, then I did a fresh install of 1.22.1 (on ubuntu)
Using the same yaml-files as before. No go Im afraid.

If I use an external postgres, nothing really happens.
If I tell the operator to create a postgres for me, It will, but then it stops.

```NAME    STATUS   ROLES                  AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-1   Ready    control-plane,master   25h   v1.22.1   192.168.10.41   <none>        Ubuntu 20.04.3 LTS   5.4.0-81-generic   docker://20.10.8
k8s-2   Ready    <none>                 25h   v1.22.1   192.168.10.42   <none>        Ubuntu 20.04.3 LTS   5.4.0-81-generic   docker://20.10.8```

Running cilium image (stable): v1.10.3

**Comment by slaurencelle** [comment] 2021-09-03 14:48
hello Tobgen,
which version of the awx-operator you use on the other kubernetes cluster ?
i have try from 0.9.0 to 0.13.0 and no luck, it was on rhel 7.x
i notice that other peaople had the same issue but on my side the awx pod is not even create and don't know what is happening ...

Stephane

**Comment by chrismeyersfsu** [comment] 2021-09-03 17:28
duplicate of https://github.com/ansible/awx-operator/issues/511

**Closed as completed by chrismeyersfsu** 2021-09-03 17:28 UTC

**Comment by tobgen** [comment] 2021-09-05 08:41
> hello Tobgen,
> which version of the awx-operator you use on the other kubernetes cluster ?
> i have try from 0.9.0 to 0.13.0 and no luck, it was on rhel 7.x
> i notice that other peaople had the same issue but on my side the awx pod is not even create and don't know what is happening ...
> 
> Stephane

I have tried with the same range of operators as you.
