### ISSUE TITLE
Using new Container Instance fails to deploy from template

### ISSUE THREAD

**Issue by u849296** [ansible/tower-operator#59] opened 2020-12-10 19:49 UTC
After creating a Container Instance and giving OCP credentials then using a template that calls this Instance the Pod never starts up and the awx-task log show the following error:

2020-12-10 19:43:21,612 DEBUG    awx.main.dispatch task 75f3a246-7e1f-4944-b162-920ea6ffcaeb starting awx.main.tasks.awx_periodic_scheduler(*[])
2020-12-10 19:43:21,621 DEBUG    awx.main.tasks Starting periodic scheduler
2020-12-10 19:43:21,624 DEBUG    awx.main.tasks Last scheduler run was: 2020-12-10 19:42:51.606794+00:00
2020-12-10 19:43:31,629 DEBUG    awx.main.dispatch task e4fdddad-a886-4e10-96b0-857a6986dd41 starting awx.main.scheduler.tasks.run_task_manager(*[])
2020-12-10 19:43:31,631 DEBUG    awx.main.scheduler Running Tower task manager.
2020-12-10 19:43:31,637 DEBUG    awx.main.scheduler Starting Scheduler
2020-12-10 19:43:31,736 ERROR    awx.main.dispatch Worker failed to run task awx.main.scheduler.tasks.run_task_manager(*[], **{}
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 86, in perform_work
    result = self.run_callable(body)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/worker/task.py", line 62, in run_callable
    return _call(*args, **kwargs)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/tasks.py", line 16, in run_task_manager
    TaskManager().schedule()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/task_manager.py", line 644, in schedule
    self._schedule()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/task_manager.py", line 632, in _schedule
    self.process_tasks(all_sorted_tasks)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/task_manager.py", line 598, in process_tasks
    self.process_pending_tasks(pending_tasks)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/task_manager.py", line 511, in process_pending_tasks
    self.start_task(task, rampart_group, task.get_jobs_fail_chain(), None)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/scheduler/task_manager.py", line 287, in start_task
    match = group.fit_task_to_most_remaining_capacity_instance(task)
TypeError: fit_task_to_most_remaining_capacity_instance() missing 1 required positional argument: 'instances'

awx-operator: 15.0.1
Openshift: 4.5.20

**Comment by metabsd** [comment] 2020-12-17 01:14
I have a similar problem. I successfully deploy it on a MicroK8s but when I try it in Openshift 4.5.22 it's not working.

I try it by using the PostgreSQL included with the operator and I also try to use external db with Binami helm chart stable postgresql. 

In both way I got the same problem.

PostgreSQL with Bitnami
```
persistence:
  enabled: true
  storageClass: thin
  size: 8Gi
volumePermissions:
  securityContext:
    runAsUser: "auto"
securityContext:
  enabled: false
containerSecurityContext:
  enabled: false
shmVolume:
  chmod:
    enabled: false
```

AWX
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
stringData:
  host: postgresql.sampleproject.svc.cluster.local
  port: '5432'
  database: awx
  username: awx
  password: awx
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  deployment_type: awx
  tower_replicas: 1
  tower_admin_user: admin
  tower_admin_email: username@domain.com
  tower_admin_password: superduperpassword
  tower_broadcast_websocket_secret: superduperpassword
  tower_ingress_type: Route
  tower_hostname: awx.apps.domain.lab.app
  tower_task_image: ansible/awx:15.0.1 # replace this with desired image
  tower_web_image: ansible/awx:15.0.1 # replace this with desired image
  external_database: true
```

I also try with all deploy by the operator
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
stringData:
  host: postgresql.poc-aci-1.svc.cluster.local
  port: '5432'
  database: awx
  username: awx
  password: awx
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  deployment_type: awx
  tower_replicas: 1
  tower_admin_user: admin
  tower_admin_email: username@domain.com
  tower_admin_password: superduperpassword
  tower_broadcast_websocket_secret: superduperpassword
  tower_ingress_type: Route
  tower_hostname: awx.apps.domain.lab.app
  tower_task_image: ansible/awx:15.0.1 # replace this with desired image
  tower_web_image: ansible/awx:15.0.1 # replace this with desired image
  tower_postgres_image: postgres:10 # replace this with the desired image
  tower_postgres_storage_class: thin
```

I experience the same problem on both.

AWX POD container `awx-task`

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/__init__.py", line 154, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/run_dispatcher.py", line 55, in handle
    reaper.reap()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/dispatch/reaper.py", line 38, in reap
    (changed, me) = Instance.objects.get_or_register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/managers.py", line 147, in get_or_register
    RegisterQueue('tower', None, 100, 0, []).register()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/management/commands/register_queue.py", line 103, in register
    self.instance_not_found_err = e
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/transaction.py", line 284, in __exit__
    connection.set_autocommit(True)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 410, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 636, in run_and_clear_commit_hooks
    func()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/signals.py", line 416, in <lambda>
    lambda: emit_activity_stream_change(activity_entry)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/main/signals.py", line 376, in emit_activity_stream_change
    summary_fields = ActivityStreamSerializer(instance).get_summary_fields(instance)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/awx/api/serializers.py", line 5004, in get_summary_fields
    if m2m_list:
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column main_credential.managed_by_tower does not exist
LINE 1: ..."."name", "main_credential"."credential_type_id", "main_cred...
```

AWX Pod Redis container
```
1:C 17 Dec 2020 01:02:11.587 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Dec 2020 01:02:11.587 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Dec 2020 01:02:11.587 # Configuration loaded
1:M 17 Dec 2020 01:02:11.588 * Running mode=standalone, port=0.
1:M 17 Dec 2020 01:02:11.588 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 17 Dec 2020 01:02:11.588 # Server initialized
1:M 17 Dec 2020 01:02:11.588 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').
1:M 17 Dec 2020 01:02:11.589 * The server is now ready to accept connections at /var/run/redis/redis.sock
```

PostgreSQL Log

```
2020-12-17 01:04:01.573 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.575 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.575 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.576 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.576 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.579 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.579 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.580 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.580 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.582 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.582 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.585 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.585 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.587 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.587 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.589 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.589 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.592 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.592 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.594 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.594 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.597 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.597 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.599 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
2020-12-17 01:04:01.599 GMT [4249] STATEMENT:  SELECT "conf_setting"."id", "conf_setting"."created", "conf_setting"."modified", "conf_setting"."key", "conf_setting"."value", "conf_setting"."user_id" FROM "conf_setting" WHERE ("conf_setting"."key" = 'OAUTH2_PROVIDER' AND "conf_setting"."user_id" IS NULL) ORDER BY "conf_setting"."id" ASC  LIMIT 1
2020-12-17 01:04:01.601 GMT [4249] ERROR:  relation "conf_setting" does not exist at character 158
...............
2020-12-17 01:05:59.521 GMT [4480] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:05:59.521 GMT [4480] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:04.043 GMT [4483] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:04.043 GMT [4483] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:08.874 GMT [4499] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:08.874 GMT [4499] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:13.560 GMT [4501] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:13.560 GMT [4501] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:18.470 GMT [4516] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:18.470 GMT [4516] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:23.034 GMT [4518] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:23.034 GMT [4518] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:27.549 GMT [4526] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:27.549 GMT [4526] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:32.402 GMT [4537] ERROR:  column main_instance.ip_address does not exist at character 47
2020-12-17 01:06:32.402 GMT [4537] STATEMENT:  SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance"."ip_address" = '172.31.1.18' AND NOT ("main_instance"."hostname" = 'awx-f56ff85d8-ck96d'))  LIMIT 1
2020-12-17 01:06:37.114 GMT [4538] ERROR:  column main_credential.managed_by_tower does not exist at character 261
2020-12-17 01:06:37.114 GMT [4538] STATEMENT:  SELECT "main_credential"."id", "main_credential"."created", "main_credential"."modified", "main_credential"."description", "main_credential"."created_by_id", "main_credential"."modified_by_id", "main_credential"."name", "main_credential"."credential_type_id", "main_credential"."managed_by_tower", "main_credential"."organization_id", "main_credential"."inputs", "main_credential"."admin_role_id", "main_credential"."use_role_id", "main_credential"."read_role_id" FROM "main_credential" INNER JOIN "main_activitystream_credential" ON ("main_credential"."id" = "main_activitystream_credential"."credential_id") WHERE "main_activitystream_credential"."activitystream_id" = 24 ORDER BY "main_credential"."name" ASC
```

**Comment by metabsd** [comment] 2020-12-17 01:21
I believe that the problem is at the PostgreSQL level because after a few minutes everything started working with the Bitnami setup.

@u849296 Can you try and share your result please :)

**Comment by bryangruneberg** [comment] 2021-01-16 20:22
Another example from the field - I've got the same situation using the operator on Digital Ocean K8S

**Comment by bryangruneberg** [comment] 2021-01-16 20:41
I think its related to this issue: https://github.com/ansible/awx/issues/1618

**Comment by tchellomello** [comment] 2021-04-26 02:32
This issue was related to https://github.com/ansible/awx/issues/8454 and the PostgreSQL at https://github.com/ansible/awx-operator/issues/59#issuecomment-747140379 is related to the database being populated during the first time which was fixed as mentioned at https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx which should be addressed on the next AWX release. 

Closing for now.

**Closed as completed by tchellomello** 2021-04-26 02:32 UTC

**Comment by miguelgmedina** [comment] 2021-08-13 12:39
Sorry for answering to a closed topic but I still have this same issue in a fresh deployment, the latest 0.12.0 operator version. I am installing it on a clean namespace. 
Same error messages than the ones reported by @metabsd. As a workaround, if I delete manually the Pod, when the ReplicaSet recreates it, everything is working again.
Kubernetes version: 1.18.5

Thanks in advance

**Comment by dberardo-com** [comment] 2022-08-07 19:42
i am facing the same issue with postgres errors on a docker compose setup (awx 21.4), is there a workaround ?

**Comment by bartowl** [comment] 2022-09-13 14:42
I had the same issue when installing awx-operator together with aws from the same kustomization.yaml. It was just too fast. Workaround for me was:
```
kubectl delete awx <instance-name>
./kustomize build . | kubectl apply -f -
```
this deleted the awx instance and re-created it with kustomize a bit later...

Have also a look in console logs of postgresql - if using old persistent storage, newly generated credentials will not match database and the migration process will never finish. In such case either pre-populate needed secrets before creating awx instance, or just ensure that no persistent postgresql storage is left over. If observed wrong passwords in postgresql logs, then you have this problem.
You may also want to look into awx-manager container of awx operator to see what is going on... it helped me.
