### ISSUE TITLE
values.yaml being ignored

### ISSUE THREAD

**Issue by castaway2000** [ansible/tower-operator#1910] opened 2024-06-27 21:45 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

the myValues.yaml file as below: 

```
AWX:
  # enable use of awx-deploy template
  enabled: true
  spec:
    admin_user: admin
    image_version: 2.13.1
    service_type: NodePort
    nodeport_port: 30004

  # configurations for external postgres instance
  postgres:
    enabled: false

  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: FooBArPAssw0rd1NotMyRE@1PW
      secretName: awx-admin-password
    secretKey:
      enabled: true
      key: test1234567890~!
      secretName: my-awx-secret-key
```

commands to deploy: 
```

    # Install AWX
    - name: "Install AWX"
      shell: bash
      run: |
        gcloud config set project anthos-kubernetes-dev
        gcloud container aws clusters get-credentials itd-dev-uswest2-anthos-aws-kyberno-cluster --location us-west1
        helm repo add awx-operator https://ansible.github.io/awx-operator/
        helm upgrade --install awx awx-operator/awx-operator --create-namespace --namespace awx -f myValues.yaml
```

please clarify a few things: first is spec in the right format and condition for the myValues.yaml file. is NodePort and its configuration correctly positioned in the myValues.yaml file. 2nd how do i declare the permissions group or userID for postgress to avoid the known issue with the pgsql path permission error? how/where do i declare what version of AWX seperate from Ansible-operator? is it all just lumped under AWX.spec? this seems to be all one option under "spec" but it is unclear what section spec this should be in. is this a global spec?

lastly the values i input into myValues.yaml do not look to be taking at all this is based on the documentation showin in the starter directory where a few examples are given along with the read the docs where it is very confusing how the configs in values.yaml are supposed to be deployed with helm.

final comments a lot of the proposed solutions to my issue are that i run a seperate net-svc.yml in the cli to fix the service. this is unacceptable as using helm to deploy all in for DR purposes would have best practices be all configs in one proceedure not two. 

can i get some clarification on all the above and can someone confirm that values.yaml data is or is not registering in deployments? 

### AWX Operator version

2.19.0

### AWX version

24.6.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

K8s managed Anthos using latest

### Modifications

no

### Steps to reproduce

use the values.yaml as shown above. 

run  `helm upgrade --install awx awx-operator/awx-operator --create-namespace --namespace awx -f myValues.yaml`

watch as the NodePort does not take as NodePort and instead deploys cluster IP, watch as the image version is ignored and instead deploys latest

### Expected results

deployment should deploy version specified and NodePort should show up as the service type. 

### Actual results

ClusterIP shows up in service type and latest version of each image is deployed. 

### Additional information

I also noticed that on top of the NodePort not being created this known issue is also persisting: https://github.com/ansible/awx-operator/issues/1770. 

Additionally i get no errors from helm during git actions deployment and having tried this 4-5 times now i notice that the web interface does not always deploy as well.

**Comment by dyhack** [comment] 2024-07-02 16:11
the same as you
`AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    admin_user: admin
    ipv6_disabled: true
    service_type: NodePort
    nodeport_port: 30180

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: 192.168.220.187
    port: 30353
    dbName: awx
    username: postgres
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: postgres
    sslmode: prefer
    type: unmanaged
  customVolumes:
    postgres:
      enabled: true
      size: 400Mi
      hostPath: /data/postgres-13
`

**Comment by castaway2000** [comment] 2024-07-02 22:37
@dyhack i realized a few things in the docs for non helm deployments. local deployments empehsize the use of kustomization over helm charts. 

my stopgap fix was to use the kustomization.yaml instructions over the helm instructions and used git actions to do the deployments automatically for me into my k8s clusters. 

Hopfully this can get you unstuck. Kustomization.yaml with kubectl apply -k ./kustomization.yaml seemed to apply all the network changes i was needed with nodeports and admin stuff. it also seemed to fix the postgress issue. 

the values.yaml issue for helm tutorial and documentation problem however still exists with all the above. but the interim fix for automated deployments is use kustomization.yaml

**Comment by dyhack** [comment] 2024-07-03 02:50
@castaway2000 
OK，thanks
mybe we should repair the helm values.yml error
It may mislead many people to configure with Helm

**Comment by djyasin** [comment] 2024-07-03 15:26
@castaway2000 has the above workaround resolved this issue for you? Are you able to use helm the way you had wanted to with this resolution?

**Comment by castaway2000** [comment] 2024-07-06 06:32
@djyasin using kustomization.yaml was the only working solution. Helm charts are completely unusable. all documented values configurations for values.yaml don't work with helm commands. this seems to be because the docs are all for kustomization.yaml and not helm charts.  all the helm chart docs seem to mislead how to put a values file together. 

so helm upgrade wont work for our needs. but kubectl apply -f kustomization.yaml worked.

**Comment by thedoubl3j** [comment] 2024-07-10 17:47
@rooftopcellist do we need to update our helm charts to resolve this or is this a limitation in helm?

**Comment by djyasin** [comment] 2024-07-24 17:33
@castaway2000 we are happy to hear that the workaround was helpful for you!

**Comment by oraNod** [comment] 2024-09-04 18:32
Hi @castaway2000 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:32 UTC
Labels: needs_triage, community, Helm
