### ISSUE TITLE
awx-ee:latest container is missing pywinrm - no module named 'winrm' (as of 2023-02-02T10:32:00+01)

### ISSUE THREAD

**Issue by prof79** [ansible/tower-operator#1214] opened 2023-02-02 09:47 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Yesterday I updated to operator 1.1.4. First I could still run my templates/workflows in a Windows environment (WinRM/Kerberos).

In the evening I wanted to start more jobs and suddenly just got errors like these up to now:

`"msg": "winrm or requests is not installed: No module named 'winrm'"`

As I found out using podman, `awx-ee:latest` as of the time of this writing doesn't seem to contain `pywinrm` any longer:

 `podman run --pull always -it quay.io/ansible/awx-ee:latest pip3 freeze | grep pywinrm`

I'm now using `awx-ee:21.11.0` as execution environment which is acceptably recent and working.

### AWX Operator version

1.1.4

### AWX version

21.11.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

Ubuntu rancher k3s v1.22.6+k3s1

### Modifications

no

### Steps to reproduce

Try to run any workflow/template connecting to Windows hosts using WinRM and Kerberos.

### Expected results

Successful connection

### Actual results

{
  "msg": "winrm or requests is not installed: No module named 'winrm'",
  "_ansible_no_log": false
}

**Comment by kurokobo** [comment] 2023-02-02 12:12
Should be tracked and fixed in awx-ee repository: https://github.com/ansible/awx-ee/issues/163

**Comment by Frewx** [comment] 2023-02-02 12:13
I am facing the same issue with AWX operator 21.10.1. I have another AWX operator deployment which is 21.0.0 just working fine.

**Comment by kurokobo** [comment] 2023-02-02 12:16
@Frewx 
As a workaround, use `quay.io/ansible/awx-ee:21.11.0` instead.

**Comment by Frewx** [comment] 2023-02-02 12:26
Changing the image worked.

**Comment by relrod** [comment] 2023-02-02 18:38
Thanks. Closing as duplicate of ansible/awx-ee#163 / ansible/awx-ee#161.

Working on fixes for these.

**Closed as completed by relrod** 2023-02-02 18:38 UTC
Labels: needs_triage, community
