### ISSUE TITLE
No way to finalize awx installation with awx-oprator

### ISSUE THREAD

**Issue by DanRod1** [ansible/tower-operator#301] opened 2021-05-10 08:51 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Hi,
I am trying to install awx by the way of awx-operator.
After several attempts to figure out what was going on  I finally decide to open this issue to move forward.
I join the manifest of my installation in a zip file. We can see the awx_web awx_task, awx_ee and redis pod to go up but not the postgres !!!
I do not find any explanation of the reason why. Coul you explain what I doing wrong ?

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: v1.20.5
* AWX install method:awx-operator

##### STEPS TO REPRODUCE

kubectl apply -f awx-kube.yaml

##### EXPECTED RESULTS

see all pod running

##### ACTUAL RESULTS

**[binfra.ansible.user@s491liak8mstr1 ~]$ kubectl get all -n awx**
_NAME READY STATUS RESTARTS AGE
pod/awx-6dd8584f68-jmwgk 4/4 Running 0 8h
pod/awx-operator-5595d6fc57-4hn55 1/1 Running 4 3d19h
pod/awx-operator-5595d6fc57-c59wq 1/1 Running 1507 3d19h

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
service/awx-operator-metrics ClusterIP 10.98.63.49 <none> 8383/TCP,8686/TCP 4d16h
service/awx-service NodePort 10.97.13.113 <none> 80:30584/TCP 3d17h

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/awx 1/1 1 1 3d17h
deployment.apps/awx-operator 2/2 2 2 4d16h

NAME DESIRED CURRENT READY AGE
replicaset.apps/awx-6dd8584f68 1 1 1 3d17h
replicaset.apps/awx-operator-5595d6fc57 2 2 2 4d16h_

##### ADDITIONAL INFORMATION

**binfra.ansible.user@s491liak8mstr1 ~]$ kubectl describe pod/awx-6dd8584f68-jmwgk -n awx**

_Name: awx-6dd8584f68-jmwgk
Namespace: awx
Priority: 0
Node: s491liak8node1/10.28.19.15
Start Time: Mon, 10 May 2021 01:59:08 +0200
Labels: app.kubernetes.io/component=awx
app.kubernetes.io/managed-by=awx-operator
app.kubernetes.io/name=awx
app.kubernetes.io/part-of=awx
app.kubernetes.io/version=19.1.0
pod-template-hash=6dd8584f68
Annotations: cni.projectcalico.org/podIP: 172.16.98.166/32
cni.projectcalico.org/podIPs: 172.16.98.166/32
Status: Running
IP: 172.16.98.166
IPs:
IP: 172.16.98.166
Controlled By: ReplicaSet/awx-6dd8584f68
Containers:
redis:
Container ID: docker://30206811bf5dc13f6f82151839aab89961dfc356336101ae61a7f5f1aff7eba7
Image: docker.io/redis:latest
Image ID: docker-pullable://redis@sha256:eff56acc5fc7b909183da93236ba09d3b8cb7d6db31d5b25e9a46dac9b5e699b
Port: <none>
Host Port: <none>
Args:
redis-server
/etc/redis.conf
State: Running
Started: Mon, 10 May 2021 01:59:10 +0200
Ready: True
Restart Count: 0
Environment: <none>
Mounts:
/data from awx-redis-data (rw)
/etc/redis.conf from awx-redis-config (ro,path="redis.conf")
/var/run/redis from awx-redis-socket (rw)
/var/run/secrets/kubernetes.io/serviceaccount from awx-token-s5vnk (ro)
awx-web:
Container ID: docker://2a0e5e17f20d6a9c4ecdf1ff89497e73fdc93bd5fbd6e00634b04d9472bcd77d
Image: quay.io/ansible/awx:19.1.0
Image ID: docker-pullable://quay.io/ansible/awx@sha256:f1327654a6e9d742f1261584d10a490e0303fabdbf352588139cbcd7d471b0b5
Port: 8052/TCP
Host Port: 0/TCP
State: Running
Started: Mon, 10 May 2021 01:59:10 +0200
Ready: True
Restart Count: 0
Limits:
cpu: 2
memory: 4Gi
Requests:
cpu: 1
memory: 2Gi
Environment:
MY_POD_NAMESPACE: awx (v1:metadata.namespace)
Mounts:
/etc/nginx/nginx.conf from awx-nginx-conf (ro,path="nginx.conf")
/etc/tower/SECRET_KEY from awx-secret-key (ro,path="SECRET_KEY")
/etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
/etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
/etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
/etc/tower/settings.py from awx-settings (ro,path="settings.py")
/var/lib/awx/projects from awx-projects (rw)
/var/lib/awx/rsyslog from rsyslog-dir (rw)
/var/run/awx-rsyslog from rsyslog-socket (rw)
/var/run/redis from awx-redis-socket (rw)
/var/run/secrets/kubernetes.io/serviceaccount from awx-token-s5vnk (ro)
/var/run/supervisor from supervisor-socket (rw)
awx-task:
Container ID: docker://af0953886182d81057adcccd8448d36a4d3440cf53143716ab2012c281df7f6a
Image: quay.io/ansible/awx:19.1.0
Image ID: docker-pullable://quay.io/ansible/awx@sha256:f1327654a6e9d742f1261584d10a490e0303fabdbf352588139cbcd7d471b0b5
Port: <none>
Host Port: <none>
Args:
/usr/bin/launch_awx_task.sh
State: Running
Started: Mon, 10 May 2021 01:59:10 +0200
Ready: True
Restart Count: 0
Limits:
cpu: 1
memory: 2Gi
Requests:
cpu: 500m
memory: 1Gi
Environment:
SUPERVISOR_WEB_CONFIG_PATH: /etc/supervisord.conf
AWX_SKIP_MIGRATIONS: 1
MY_POD_UID: (v1:metadata.uid)
MY_POD_IP: (v1:status.podIP)
MY_POD_NAMESPACE: awx (v1:metadata.namespace)
Mounts:
/etc/tower/SECRET_KEY from awx-secret-key (ro,path="SECRET_KEY")
/etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
/etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
/etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
/etc/tower/settings.py from awx-settings (ro,path="settings.py")
/var/lib/awx/projects from awx-projects (rw)
/var/lib/awx/rsyslog from rsyslog-dir (rw)
/var/run/awx-rsyslog from rsyslog-socket (rw)
/var/run/receptor from receptor-socket (rw)
/var/run/redis from awx-redis-socket (rw)
/var/run/secrets/kubernetes.io/serviceaccount from awx-token-s5vnk (ro)
/var/run/supervisor from supervisor-socket (rw)
awx-ee:
Container ID: docker://285aaf5a2556cedb574e2d00c683f1a2e59cef753b14f4f4c1dfcaf1be88886b
Image: quay.io/ansible/awx-ee:0.2.0
Image ID: docker-pullable://quay.io/ansible/awx-ee@sha256:9875087f0cf8bf93d4e4fa58461ab52c5d8bd2516bcb795b11a871fcf5ace758
Port: <none>
Host Port: <none>
Args:
receptor
--config
/etc/receptor.conf
State: Running
Started: Mon, 10 May 2021 01:59:11 +0200
Ready: True
Restart Count: 0
Environment: <none>
Mounts:
/etc/receptor.conf from awx-receptor-config (ro,path="receptor.conf")
/var/lib/awx/projects from awx-projects (rw)
/var/run/receptor from receptor-socket (rw)
/var/run/secrets/kubernetes.io/serviceaccount from awx-token-s5vnk (ro)
Conditions:
Type Status
Initialized True
Ready True
ContainersReady True
PodScheduled True
Volumes:
awx-application-credentials:
Type: Secret (a volume populated by a Secret)
SecretName: awx-app-credentials
Optional: false
awx-secret-key:
Type: Secret (a volume populated by a Secret)
SecretName: awx-secret-key
Optional: false
awx-settings:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-nginx-conf:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-redis-config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-redis-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
awx-redis-data:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
supervisor-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
rsyslog-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
receptor-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
rsyslog-dir:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
awx-receptor-config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-projects:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: postgrespvc
ReadOnly: false
ansible-cfg:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-extra-config
Optional: false
awx-token-s5vnk:
Type: Secret (a volume populated by a Secret)
SecretName: awx-token-s5vnk
Optional: false
QoS Class: Burstable
Node-Selectors: <none>
Tolerations: node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events: <none>_

**[binfra.ansible.user@s491liak8mstr1 ~]$ kubectl describe deployment.apps/awx -n awx**
_Name: awx
Namespace: awx
CreationTimestamp: Thu, 06 May 2021 16:52:52 +0200
Labels: app.kubernetes.io/component=awx
app.kubernetes.io/managed-by=awx-operator
app.kubernetes.io/name=awx
app.kubernetes.io/part-of=awx
app.kubernetes.io/version=19.1.0
Annotations: deployment.kubernetes.io/revision: 1
Selector: app.kubernetes.io/component=awx,app.kubernetes.io/managed-by=awx-operator,app.kubernetes.io/name=awx
Replicas: 1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType: RollingUpdate
MinReadySeconds: 0
RollingUpdateStrategy: 25% max unavailable, 25% max surge
Pod Template:
Labels: app.kubernetes.io/component=awx
app.kubernetes.io/managed-by=awx-operator
app.kubernetes.io/name=awx
app.kubernetes.io/part-of=awx
app.kubernetes.io/version=19.1.0
Service Account: awx
Containers:
redis:
Image: docker.io/redis:latest
Port: <none>
Host Port: <none>
Args:
redis-server
/etc/redis.conf
Environment: <none>
Mounts:
/data from awx-redis-data (rw)
/etc/redis.conf from awx-redis-config (ro,path="redis.conf")
/var/run/redis from awx-redis-socket (rw)
awx-web:
Image: quay.io/ansible/awx:19.1.0
Port: 8052/TCP
Host Port: 0/TCP
Limits:
cpu: 2
memory: 4Gi
Requests:
cpu: 1
memory: 2Gi
Environment:
MY_POD_NAMESPACE: (v1:metadata.namespace)
Mounts:
/etc/nginx/nginx.conf from awx-nginx-conf (ro,path="nginx.conf")
/etc/tower/SECRET_KEY from awx-secret-key (ro,path="SECRET_KEY")
/etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
/etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
/etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
/etc/tower/settings.py from awx-settings (ro,path="settings.py")
/var/lib/awx/projects from awx-projects (rw)
/var/lib/awx/rsyslog from rsyslog-dir (rw)
/var/run/awx-rsyslog from rsyslog-socket (rw)
/var/run/redis from awx-redis-socket (rw)
/var/run/supervisor from supervisor-socket (rw)
awx-task:
Image: quay.io/ansible/awx:19.1.0
Port: <none>
Host Port: <none>
Args:
/usr/bin/launch_awx_task.sh
Limits:
cpu: 1
memory: 2Gi
Requests:
cpu: 500m
memory: 1Gi
Environment:
SUPERVISOR_WEB_CONFIG_PATH: /etc/supervisord.conf
AWX_SKIP_MIGRATIONS: 1
MY_POD_UID: (v1:metadata.uid)
MY_POD_IP: (v1:status.podIP)
MY_POD_NAMESPACE: (v1:metadata.namespace)
Mounts:
/etc/tower/SECRET_KEY from awx-secret-key (ro,path="SECRET_KEY")
/etc/tower/conf.d/credentials.py from awx-application-credentials (ro,path="credentials.py")
/etc/tower/conf.d/execution_environments.py from awx-application-credentials (ro,path="execution_environments.py")
/etc/tower/conf.d/ldap.py from awx-application-credentials (ro,path="ldap.py")
/etc/tower/settings.py from awx-settings (ro,path="settings.py")
/var/lib/awx/projects from awx-projects (rw)
/var/lib/awx/rsyslog from rsyslog-dir (rw)
/var/run/awx-rsyslog from rsyslog-socket (rw)
/var/run/receptor from receptor-socket (rw)
/var/run/redis from awx-redis-socket (rw)
/var/run/supervisor from supervisor-socket (rw)
awx-ee:
Image: quay.io/ansible/awx-ee:0.2.0
Port: <none>
Host Port: <none>
Args:
receptor
--config
/etc/receptor.conf
Environment: <none>
Mounts:
/etc/receptor.conf from awx-receptor-config (ro,path="receptor.conf")
/var/lib/awx/projects from awx-projects (rw)
/var/run/receptor from receptor-socket (rw)
Volumes:
awx-application-credentials:
Type: Secret (a volume populated by a Secret)
SecretName: awx-app-credentials
Optional: false
awx-secret-key:
Type: Secret (a volume populated by a Secret)
SecretName: awx-secret-key
Optional: false
awx-settings:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-nginx-conf:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-redis-config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-redis-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
awx-redis-data:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
supervisor-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
rsyslog-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
receptor-socket:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
rsyslog-dir:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
awx-receptor-config:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-awx-configmap
Optional: false
awx-projects:
Type: PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
ClaimName: postgrespvc
ReadOnly: false
ansible-cfg:
Type: ConfigMap (a volume populated by a ConfigMap)
Name: awx-extra-config
Optional: false
Conditions:
Type Status Reason
---- ------ ------
Progressing True NewReplicaSetAvailable
Available True MinimumReplicasAvailable
OldReplicaSets: awx-6dd8584f68 (1/1 replicas created)
NewReplicaSet: <none>
Events: <none>_

##### AWX-OPERATOR LOGS
Name: awx-operator
Namespace: awx
CreationTimestamp: Wed, 05 May 2021 17:53:48 +0200
Labels: <none>
Annotations: deployment.kubernetes.io/revision: 1
Selector: name=awx-operator
Replicas: 2 desired | 2 updated | 2 total | 1 available | 1 unavailable
StrategyType: RollingUpdate
MinReadySeconds: 0
RollingUpdateStrategy: 25% max unavailable, 25% max surge
Pod Template:
Labels: name=awx-operator
Service Account: awx-operator
Containers:
awx-operator:
Image: quay.io/ansible/awx-operator:0.9.0
Port: <none>
Host Port: <none>
Liveness: http-get http://:6789/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
Environment:
WATCH_NAMESPACE:
POD_NAME: (v1:metadata.name)
OPERATOR_NAME: awx-operator
ANSIBLE_GATHERING: explicit
Mounts:
/tmp/ansible-operator/runner from runner (rw)
Volumes:
runner:
Type: EmptyDir (a temporary directory that shares a pod's lifetime)
Medium:
SizeLimit: <unset>
Conditions:
Type Status Reason
---- ------ ------
Progressing True NewReplicaSetAvailable
Available False MinimumReplicasUnavailable
OldReplicaSets: <none>
NewReplicaSet: awx-operator-5595d6fc57 (2/2 replicas created)
Events: <none>
[kube-awx.zip](https://github.com/ansible/awx-operator/files/6450782/kube-awx.zip)

**Comment by tchellomello** [comment] 2021-05-11 05:18
>> I join the manifest of my installation in a zip file. We can see the awx_web awx_task, awx_ee and redis pod to go up but not the postgres !!!
I do not find any explanation of the reason why. Coul you explain what I doing wrong ?
>>

@DanRod1  the issue is explained here:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: awx-postgres.production-real.fr
  port: "5432"
  database: AWX-PGRES
  username: admin
  password: admin
type: Opaque
```

  Since you configured the your `awx-postgres-configuration` with the data above, the `awx-operator` see this as an external database because it is missing the attribute `type: managed`  (https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/database_configuration.yml#L71-L105)

Here is an example of a secret for managed PostgreSQL instances:

```yaml
apiVersion: v1
data:
  database: YXd4
  host: YXd4LWRlbW8tZGV2ZWwtcG9zdGdyZXM=
  password: SXFVdDJxNmdCRGdFUjQ0MnQ1bFpJanFJcERmSTlJMEI=
  port: NTQzMg==
  type: bWFuYWdlZA==  ### <=== type: managed
  username: YXd4
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-demo-devel
    app.kubernetes.io/part-of: awx-demo-devel
  name: awx-demo-devel-postgres-configuration
  namespace: default
type: Opaque
```

If you modify your `awx-postgres-configuration` secret and add the `type: managed`, make sure also the `host` looks accurate. 

For testing, try to a create a fresh `awx` without passing any special attributes or parameters and you will see the PostgreSQL statefulset being created.

**Comment by DanRod1** [comment] 2021-05-11 13:28
Hi, thanks for the reply.
To be sure to understood your answer this means that all the parameters of the "datasource" are encrypted ?
Is it usefull ?

**Comment by tchellomello** [comment] 2021-05-11 19:11
@DanRod1 not really.. that is an encoded string. You could modify yours like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: awx-postgres
  port: "5432"
  database: AWX-PGRES
  username: admin
  password: admin
  type: managed
type: Opaque
```

The PostgreSQL statefulset  will only be deployed if the `type: managed` is found on the secret. Since you manually created the secret, you have to add it for managed `sts`.

**Comment by DanRod1** [comment] 2021-05-12 09:11
Once again thanks a lot for your time and your anwsers, I appriciate your help.
May I abuse of your time with a other question ? How can I personalize the name of the claim of the persistent volume for postgres I don't see in the documentation the parameter for this ?

**Comment by tchellomello** [comment] 2021-05-12 14:41
@DanRod1  you are very welcome and it seems the issue is now fixed. :fireworks: 

In regards to the `PVC` name, on the current architecture, the PostgreSQL is a `statefulset` that claims the storage using a `volumeClaimTemplate`.  As you can see at https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage, and looking at our code we are using the snippet below:

```yaml
   volumeClaimTemplates:
     - metadata:
         name: postgres
       spec:
         accessModes:
           - ReadWriteOnce
```

 Because of the use of the `metadata` the PVC name shall be: `postgres` + `awx-name` + `sts-instance`. So assuming your `AWX` is named `testing-awx`, the PVC created will be `postgres-testing-awx-0`. 

Maybe what you can do is to modify the `metadata`, however, `volumeClaimTemplates` has a different workflow as mentioned above.

**Comment by DanRod1** [comment] 2021-05-17 08:07
Thanks for your answers, may i suggest a new parametre like tower_postgres_storage_claim ?

**Comment by DanRod1** [comment] 2021-05-17 13:31
Also I do not understand why the service created is a NodePort type wherease I specify the tower_ingress-type to Ingress and the tower_hostname: awx-k8s.lab-real.local.
Here is the output :
**[binfra.ansible.user@s491liak8mstr1 ~]$ kubectl get all -n awx**
NAME READY STATUS RESTARTS AGE
pod/awx-85d7cbfb8-nfq2m 4/4 Running 0 7m29s
pod/awx-operator-5595d6fc57-4hn55 1/1 Running 4 11d
pod/awx-operator-5595d6fc57-6z5xp 1/1 Running 2057 5d3h
pod/awx-postgres-0 1/1 Running 0 7m46s

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
service/awx-operator-metrics ClusterIP 10.98.63.49 <none> 8383/TCP,8686/TCP 11d
service/awx-postgres ClusterIP None <none> 5432/TCP 7m46s
**service/awx-service NodePort 10.108.108.18 <none> 80:32455/TCP 7m32s**

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/awx 1/1 1 1 7m30s
deployment.apps/awx-operator 2/2 2 2 11d

NAME DESIRED CURRENT READY AGE
replicaset.apps/awx-85d7cbfb8 1 1 1 7m30s
replicaset.apps/awx-operator-5595d6fc57 2 2 2 11d

NAME READY AGE
statefulset.apps/awx-postgres 1/1 7m47s

**Closed as completed** 2021-05-19 09:19 UTC

**Comment by DanRod1** [comment] 2021-05-19 09:20
I have still some troubles but the subject is with the network termination so I close this issue to open an another
