### ISSUE TITLE
@MacBook-Pro ~ % helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator Error: INSTALLATION FAILED: Chart.yaml file is missing

### ISSUE THREAD

**Issue by eashweragero101** [ansible/tower-operator#1634] opened 2023-11-13 17:40 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

eashwer.kumar@MacBook-Pro ~ % helm search repo awx-operator
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	2.7.2        	2.7.2      	A Helm chart for the AWX Operator
eashwer.kumar@MacBook-Pro ~ % helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
Error: INSTALLATION FAILED: Chart.yaml file is missing

### AWX Operator version

2.7.2

### AWX version

2.7.2

### Kubernetes platform

minikube

### Kubernetes/Platform version

12.7

### Modifications

no

### Steps to reproduce

eashwer.kumar@MacBook-Pro ~ % helm search repo awx-operator
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	2.7.2        	2.7.2      	A Helm chart for the AWX Operator
eashwer.kumar@MacBook-Pro ~ % helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
Error: INSTALLATION FAILED: Chart.yaml file is missing

### Expected results

installation on miniqube 

### Actual results

eashwer.kumar@MacBook-Pro ~ % helm search repo awx-operator
NAME                     	CHART VERSION	APP VERSION	DESCRIPTION                      
awx-operator/awx-operator	2.7.2        	2.7.2      	A Helm chart for the AWX Operator
eashwer.kumar@MacBook-Pro ~ % helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
Error: INSTALLATION FAILED: Chart.yaml file is missing

### Additional information

the steps to install awx fails on kubernetes 

### Operator Logs

no log

**Comment by eashweragero101** [comment] 2023-11-13 17:40
https://www.techbeatly.com/install-ansible-awx-on-kubernetes/ followed this guide

**Comment by fosterseth** [comment] 2023-11-15 18:30
can you try the installation guide outlined here? https://github.com/kurokobo/awx-on-k3s/blob/main/tips/alternative-methods.md#helm

**Comment by oraNod** [comment] 2024-09-04 18:33
Hi @eashweragero101 

The helm chart code has moved to a new repository, [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm). You can find more information about this move in the recent forum post about [changes to the AWX operator installation methods](https://forum.ansible.com/t/upcoming-changes-to-awx-operator-installation-methods/7598).

We now plan to close this issue because it is no longer relevant to the code in this repository. If you think the issue is still valid and needs to be fixed, please recreate it in the [`ansible/awx-operator-helm`](https://github.com/ansible-community/awx-operator-helm) repository.

Thank you.

**Closed as completed by oraNod** 2024-09-04 18:33 UTC
Labels: needs_triage, community, Helm
