### ISSUE TITLE
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

### ISSUE THREAD

**Issue by 11philip22** [ansible/tower-operator#1813] opened 2024-04-09 08:41 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi, I am trying to install the awx operator on digital ocean kubernetes.  
When I run `helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator` my postgres container fails to start with the error `mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`.  
When I describe the postgres container I see that `PGDATA` is set to `/var/lib/pgsql/data/pgdata` and not `/var/lib/pgsql/data/userdata`
![image](https://github.com/ansible/awx-operator/assets/26529935/b73b6aa4-92d8-4802-9e1f-b2d6c59c9238)
How do i get this to work?

### AWX Operator version

ansible-operator: v1.34.0

### AWX version

How can I see?

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29.1-do.0

### Modifications

no

### Steps to reproduce

```shell
helm repo add awx-operator https://ansible.github.io/awx-operator/
helm install -n awx --create-namespace my-awx-operator awx-operator/awx-operator
```

### Expected results

I expect my awx postgres container to be created.

### Actual results

My database container throws this error
`mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`

**Comment by TheRealHaoLiu** [comment] 2024-04-09 14:34
dupe of https://github.com/ansible/awx-operator/issues/1770 see https://github.com/ansible/awx-operator/issues/1770#issuecomment-2031118430 for workaround

in next release you can use the postgres init container to initialize the PGDATA directory see https://github.com/ansible/awx-operator/pull/1805

**Closed as completed by TheRealHaoLiu** 2024-04-09 14:34 UTC
Labels: needs_triage, community

**Comment by 11philip22** [comment] 2024-04-09 17:09
ah thank you
