### ISSUE TITLE
Ansible AWX is not displaying the job output properly

### ISSUE THREAD

**Issue by CatchKarthik** [ansible/tower-operator#856] opened 2022-04-01 20:23 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When we run the job template, we can see the output logs of the job while the job is running. But after the job is completed, the contents in the output log is not displaying properly. We see blank greyed out lines instead of the output

##### ENVIRONMENT
* AWX version: 20.1.0
* Operator version: 0.20.0
* Kubernetes version: 1.19
* AWX install method: basic install on kubernetes

##### STEPS TO REPRODUCE

1. Run a job template
2. Check the output of the job log after job completes.

##### EXPECTED RESULTS

The job output should be displayed properly

##### ACTUAL RESULTS

The job output contents are not getting displayed properly

##### ADDITIONAL INFORMATION

<img width="1779" alt="image001" src="https://user-images.githubusercontent.com/54074222/161336164-77ee235e-16aa-4f8e-a87c-4c214fba841f.png">

**Comment by rguhr** [comment] 2022-04-01 21:03
That's not an awx-operator issue.
Have a look at https://github.com/ansible/awx/issues/11765

What you can try:
* Fix all warnings that are produced by your playbook (for example the deprecation warning on your picture)
* Use AWX: 19.5.0
* Append `?job_output.not__stdout__startswith=[WARNING]` or maybe just `?job_output` to the url

**Comment by jbouse** [comment] 2022-04-05 00:24
I've experienced this same behavior myself. I had noticed it happening both on successfully and failed jobs so I hadn't been able to isolate a reason yet.

**Comment by nixocio** [comment] 2022-04-05 15:17
Hey @CatchKarthik, thanks for filing this issue. 

This one is a dupe of https://github.com/ansible/awx/issues/11765. There is an open PR to address that one.

**Closed as completed by nixocio** 2022-04-05 15:17 UTC
Labels: needs_triage
