### ISSUE TITLE
ipv6_disabled - Unknown field in com.ansible.awx.v1beta1.AWX.spec

### ISSUE THREAD

**Issue by AMC-7** [ansible/tower-operator#1192] opened 2023-01-18 09:01 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

A fresh install of the awx-operator failed to come up when disabling ipv6 using the `ipv6_disabled` property due to it being an unknown field.

`"Error: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(AWX.spec): unknown field \"ipv6_disabled\" in com.ansible.awx.v1beta1.AWX.spec"`

This is the method invocation
```
"invocation": {
    "module_args": {
      "name": "awx-operator",
      "chart_ref": "awx-operator/awx-operator",
      "release_namespace": "awx",
      "create_namespace": true,
      "kubeconfig": "/home/platform-usr/.kube/config",
      "values": {
        "AWX": {
          "enabled": true,
          "name": "awx",
          "spec": {
            "hostname": "awx.domain.io",
            "ingress_annotations": "kubernetes.io/ingress.class: haproxy\n",
            "ingress_tls_secret": "awx-ingress-default-ssl",
            "ingress_type": "ingress",
            "ipv6_disabled": true
          }
        }
      },
      "release_name": "awx-operator",
      "release_values": {
        "AWX": {
          "enabled": true,
          "name": "awx",
          "spec": {
            "hostname": "awx.domain.io",
            "ingress_annotations": "kubernetes.io/ingress.class: haproxy\n",
            "ingress_tls_secret": "awx-ingress-default-ssl",
            "ingress_type": "ingress",
            "ipv6_disabled": true
          }
        }
      },
      "release_state": "present",
      "values_files": [],
      "update_repo_cache": false,
      "disable_hook": false,
      "force": false,
      "purge": true,
      "wait": false,
      "atomic": false,
      "replace": false,
      "skip_crds": false,
      "validate_certs": true,
      "binary_path": null,
      "chart_repo_url": null,
      "chart_version": null,
      "context": null,
      "wait_timeout": null,
      "timeout": null,
      "history_max": null,
      "host": null,
      "ca_cert": null,
      "api_key": null
    }
  }
``` 

### AWX Operator version

1.1.3

### AWX version

v21.10.2

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.8+rke2r1

### Modifications

no

### Steps to reproduce

Using an existing k8s cluster and helm, install awx-operator 1.1.3.

### Expected results

awx to be up and running

### Actual results

Error received 

### Additional information

We're looking to disable ipv6 because nginx throws an error (and causes crashloopbackoff) when the awx-web container is trying to start:

`nginx: [emerg] socket() [::]:8052 failed (97: Address family not supported by protocol)`

**Comment by rooftopcellist** [comment] 2023-01-18 16:39
I was unable to reproduce with the operator deployed from `devel` with the following AWX CR:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  ipv6_disabled: true
...
```

It gets properly set in the nginx.conf too:

```
$ $ oc exec deployment/awx -c awx-web bash -- cat /etc/nginx/nginx.conf | grep "listen 8052" -B1
    server {
                listen 8052 default_server;
```

I tried this with the 1.1.3 awx-operator release as well and could not reproduce.  (I built the image locally from that release tag, so _maybe_ the image on quay.io is wrong somehow?)


-----------------------
I just realized you are using helm, maybe the helm install is pointed to an old awx-operator image somehow?

**Comment by AMC-7** [comment] 2023-01-19 11:03
Yes, on the face of it, it should work. I too wonder if the helm chart is pointing to an old version of the schema somehow. I'm going to look to build from source by packaging up and specifying the chart ref as a .tgz.

**Comment by AMC-7** [comment] 2023-01-19 11:03
Yes, on the face of it, it should work. I too wonder if the helm chart is pointing to an old version of the schema somehow. 

I'm going to look to build from source.

**Comment by djyasin** [comment] 2023-01-25 18:31
@AMC-7 
We recently released this fix in 1.1.4. Could you give that release a try to see if this resolves the issue for you?

**Comment by AMC-7** [comment] 2023-01-26 13:34
@djyasin 
I'm unable to download the operator.

```
{
  "stdout": "",
  "stderr": "Error: failed to download \"awx-operator/awx-operator\"\n",
  "command": "/usr/local/bin/helm show chart awx-operator/awx-operator",
  "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: failed to download \"awx-operator/awx-operator\"\n",
  "invocation": {
    "module_args": {
      "name": "awx-operator",
      "chart_ref": "awx-operator/awx-operator",
      "release_namespace": "awx",
      "create_namespace": true,
      "kubeconfig": "/home/platform-usr/.kube/config",
      "values": {
        "AWX": {
          "enabled": true,
          "name": "awx",
          "spec": {
            "hostname": "awx-test.domain.io",
            "ingress_annotations": "kubernetes.io/ingress.class: haproxy\n",
            "ingress_tls_secret": "awx-ingress-default-ssl",
            "ingress_type": "ingress",
            "ipv6_disabled": true
          }
        }
      },
      "release_name": "awx-operator",
      "release_values": {
        "AWX": {
          "enabled": true,
          "name": "awx",
          "spec": {
            "hostname": "awx-test.domain.io",
            "ingress_annotations": "kubernetes.io/ingress.class: haproxy\n",
            "ingress_tls_secret": "awx-ingress-default-ssl",
            "ingress_type": "ingress",
            "ipv6_disabled": true
          }
        }
      },
      "release_state": "present",
      "values_files": [],
      "update_repo_cache": false,
      "disable_hook": false,
      "force": false,
      "purge": true,
      "wait": false,
      "atomic": false,
      "replace": false,
      "skip_crds": false,
      "validate_certs": true,
      "binary_path": null,
      "chart_repo_url": null,
      "chart_version": null,
      "context": null,
      "wait_timeout": null,
      "timeout": null,
      "history_max": null,
      "host": null,
      "ca_cert": null,
      "api_key": null
    }
  },
  "stdout_lines": [],
  "stderr_lines": [
    "Error: failed to download \"awx-operator/awx-operator\""
  ],
  "_ansible_no_log": null,
  "changed": false
}
```

I searched helm locally and found the following errors:
- ssl cert error 
- 404 error 

```
helm search repo awx-operator --versions --version "1.1.4"
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
awx-operator/awx-operator       1.1.4           1.1.4           A Helm chart for the AWX Operator

helm show chart awx-operator/awx-operator --debug
show.go:195: [debug] Original chart version: ""
Error: Get "https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz": x509: certificate signed by unknown authority
helm.go:84: [debug] Get "https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz": x509: certificate signed by unknown authority

helm show chart awx-operator/awx-operator --debug --insecure-skip-tls-verify
show.go:195: [debug] Original chart version: ""
Error: failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz : 404 Not Found
helm.go:84: [debug] failed to fetch https://ansible.github.io/awx-operator/awx-operator-1.1.4.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:89
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:42
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:100
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:749
main.runShow
        helm.sh/helm/v3/cmd/helm/show.go:201
main.newShowCmd.func4
        helm.sh/helm/v3/cmd/helm/show.go:121
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```

**Comment by SnelsSM** [comment] 2023-02-09 12:43
Hi!
So... Release 1.1.4 has been installed. But the "ipv6_disabled" field is still unknown.

![image](https://user-images.githubusercontent.com/6932851/217815687-8737afae-c52a-4da1-b264-c61a2be16d89.png)

**Comment by rooftopcellist** [comment] 2023-03-02 03:07
The issue of being unable to download the operator has been fixed and it seems this is unreproducible.  I am going to go ahead a close this.  Please open a new issue with a link back if you are still experiencing this issue on the latest release.

**Closed as completed by rooftopcellist** 2023-03-02 03:07 UTC
Labels: needs_triage, community

**Comment by AMC-7** [comment] 2023-03-07 21:12
An old version of the AWX CRD was present on the cluster! After removing, the install worked as expected using helm.
