### ISSUE TITLE
how to upgrade from 0.13.0 to 0.14.0

### ISSUE THREAD

**Issue by nbari** [ansible/tower-operator#582] opened 2021-10-05 13:53 UTC
Hi, sorry if this is very basic, but wondering how to upgrade to latest `0.14.0`, I installed the operator `0.13.0` using: 

    kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml

> The URL is not present anymore

Should I edit the current operator and change the version, something like:

     kubectl edit deployment.apps/awx-operator

Could someone please share the steps?

**Comment by vrubiolo** [comment] 2021-10-05 14:15
Hi @nbari , it looks like you might need to delete the current operator Deployment and recreate it, cf https://github.com/ansible/awx-operator#upgrading

**Comment by tgruezi** [comment] 2021-10-05 14:22
hi @vrubiolo is there a way to delete the operator and without removing all the resources?

**Comment by nbari** [comment] 2021-10-05 14:23
Is there a way to delete the current operator without removing the exiting resources?

**Comment by vrubiolo** [comment] 2021-10-05 14:38
Sorry I don't know. I think so (as the operator deployment and AWX itself are two different things) but I cannot be sure as I have not done it.
This warrants a doc update to me. You might want to ask in the IRC channel as well.

**Comment by kurokobo** [comment] 2021-10-05 15:54
In my case, to upgrade AWX Operator and related AWX instance, delete existing AWX Operator and some unnecessary resources first,

```bash
kubectl -n default delete deployment awx-operator
kubectl -n default delete serviceaccount awx-operator
kubectl -n default delete clusterrolebinding awx-operator
kubectl -n default delete clusterrole awx-operator
```

then simply re-deploy new AWX Operator.

```bash
# Prepare required files
git clone https://github.com/ansible/awx-operator.git
cd awx-operator
git checkout 0.14.0

# Deploy new AWX Operator
export NAMESPACE=<Name of the namespace where your old AWX instanse exists>
make deploy
```

Once the new AWX Operator is up and running, it will start rolling out a new version of the AWX instance automatically based on the old awx resource definition.

I don't know if it will suit your use case perfectly because of the particular configuration for my use case, but there are some notes in my repository that might be helpful: <https://github.com/kurokobo/awx-on-k3s/blob/main/tips/upgrade-operator.md>

It is strongly recommended that [making a backup](https://github.com/ansible/awx-operator/tree/devel/roles/backup) before you start working.

**Comment by vrubiolo** [comment] 2021-10-06 10:15
@kurokobo : thanks for the good pointers, your repo is very interesting indeed. I am also running using K3S and looking into the `Ingress` specifics once AWX is deployed to make it accessible from outside.

**Comment by Commifreak** [comment] 2021-10-07 05:56
Why is that (https://github.com/ansible/awx-operator/issues/582#issuecomment-934536812) not mentioned here: https://github.com/ansible/awx-operator#upgrading ? This completely changes the way to deploy/update (in my eyes).

The upgrading manual says `you will want to delete your existing awx-operator service account, role and role binding.` but not how?

Confusing :(

**Comment by mrwiora** [comment] 2021-10-07 12:12
thx @kurokobo - created a PR containing your instructions :)
@nbari: thanks for asking the question - actually you were obviously not the only one struggling with this new way to go :)

**Comment by Commifreak** [comment] 2021-10-13 06:35
Since I had some issues with the whole old cluster, I backed everything up and created a new with restoring: https://github.com/ansible/awx-operator/issues/489#issuecomment-941964950

**Comment by chofstede** [comment] 2021-10-15 10:51
I can confirm, that Inventory-Sync based from project works fine again in AWX 19.4.0 
I think this issue can be closed.

**Comment by rooftopcellist** [comment] 2023-12-01 22:21
It looks as though this issue has been resolved with documentation to help with upgrading from 0.13.0 --> 0.14.0.
* https://github.com/ansible/awx-operator/pull/593

**Closed as completed by rooftopcellist** 2023-12-01 22:21 UTC
