### ISSUE TITLE
Operator helm chart rolesbinding namespace subject

### ISSUE THREAD

**Issue by apenen** [ansible/tower-operator#941] opened 2022-06-08 09:15 UTC
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Helm chart must use variable {{ .Release.Namespace }} on rolebinding and clusterrolebinding subject namespace.
Now is forced to awx.

##### ENVIRONMENT
* Operator version: 0.22.0
* Kubernetes version: 1.20
* AWX install method: helm

##### STEPS TO REPRODUCE
Install operator with helm on other namespace than awx.

##### EXPECTED RESULTS
Rolebinding and clusterrolebinding set subject to installed namespace

##### ACTUAL RESULTS
Rolebinding and clusterrolebinding set subject to awx namespace.

**Comment by fosterseth** [comment] 2022-06-08 15:17
duplicate of https://github.com/ansible/awx-operator/issues/907

**Closed as completed by fosterseth** 2022-06-08 15:17 UTC
